// 노아 전용 리프레임 라이브러리 — 사용자가 큐레이션한 트리거→오해→리프레임 500개.
// noah-reframes.txt에서 자동 생성(scripts/ingest 일회성). 파서가 입력과 매칭해 노아 본인의 균형 잡힌 해석을 surface.
export const REFRAMES = [
  { cat: "A", trigger: "“이번 주 WFH 며칠이야?”", misread: "감시하나?", reframe: "단순 일정 확인일 수 있다." },
  { cat: "A", trigger: "“이거 오늘 안에 가능해?”", misread: "압박하나?", reframe: "우선순위 확인일 수 있다." },
  { cat: "A", trigger: "“왜 이렇게 했어?”", misread: "내 판단을 못 믿나?", reframe: "의사결정 배경을 묻는 것일 수 있다." },
  { cat: "A", trigger: "“다른 옵션은 봤어?”", misread: "내 방식이 틀렸다는 뜻인가?", reframe: "리스크 체크일 수 있다." },
  { cat: "A", trigger: "“슬라이드 제목이 좀 애매한데?”", misread: "나를 깎아내리나?", reframe: "메시지 명확화 요청일 수 있다." },
  { cat: "A", trigger: "“이건 고객에게 어떻게 설명할 거야?”", misread: "내가 설명 못한다고 보나?", reframe: "커뮤니케이션 준비일 수 있다." },
  { cat: "A", trigger: "“잠깐 같이 보자.”", misread: "문제 생겼나?", reframe: "빠른 싱크업일 수 있다." },
  { cat: "A", trigger: "“이 부분은 좀 더 다듬자.”", misread: "내 결과물이 부족한가?", reframe: "완성도 향상 과정일 수 있다." },
  { cat: "A", trigger: "“너무 빨리 끝낸 거 아니야?”", misread: "의심하나?", reframe: "범위와 검증 수준을 확인하는 것일 수 있다." },
  { cat: "A", trigger: "“누가 리뷰했어?”", misread: "나를 못 믿나?", reframe: "프로세스 확인일 수 있다." },
  { cat: "A", trigger: "“이건 A랑도 같이 리뷰하자.”", misread: "나를 혼자 못 믿는구나", reframe: "이해관계자 alignment일 수 있다." },
  { cat: "A", trigger: "“고객에게 바로 보내진 말고 먼저 공유해줘.”", misread: "통제하려 하나?", reframe: "메시지 리스크 관리일 수 있다." },
  { cat: "A", trigger: "“이건 좀 기다리자.”", misread: "일부러 막나?", reframe: "타이밍 조율일 수 있다." },
  { cat: "A", trigger: "“너무 많이 만들 필요 없어.”", misread: "내 성장을 막나?", reframe: "범위 관리일 수 있다." },
  { cat: "A", trigger: "“지금은 이 일에 집중하자.”", misread: "내 아이디어를 무시하나?", reframe: "현재 우선순위가 다를 수 있다." },
  { cat: "A", trigger: "“그건 나중에 해도 돼.”", misread: "내 프로젝트가 가치 없나?", reframe: "타이밍 문제일 수 있다." },
  { cat: "A", trigger: "“간단히 요약해줘.”", misread: "내가 장황하다는 뜻인가?", reframe: "의사결정용 압축을 원하는 것일 수 있다." },
  { cat: "A", trigger: "“디테일은 빼도 돼.”", misread: "내가 한 노력이 중요하지 않나?", reframe: "청중 수준에 맞추려는 것일 수 있다." },
  { cat: "A", trigger: "“너 혼자 다 하지 말고 공유해.”", misread: "내가 독단적이라는 뜻인가?", reframe: "지식 분산 요청일 수 있다." },
  { cat: "A", trigger: "“이건 팀 차원에서 해야 해.”", misread: "내 공을 뺏나?", reframe: "확산을 위해 조직화하는 것일 수 있다." },
  { cat: "A", trigger: "“내가 보기엔 아직 early stage야.”", misread: "내 실력을 낮게 보나?", reframe: "배포 준비도에 대한 의견일 수 있다." },
  { cat: "A", trigger: "“고객 반응을 먼저 보자.”", misread: "내 판단을 안 믿나?", reframe: "실제 validation을 원하는 것일 수 있다." },
  { cat: "A", trigger: "“왜 이게 필요한지 설명해줘.”", misread: "가치 없다고 생각하나?", reframe: "business case를 묻는 것일 수 있다." },
  { cat: "A", trigger: "“기존 툴과 차이가 뭐야?”", misread: "베낀 거라고 생각하나?", reframe: "차별점을 정리할 기회일 수 있다." },
  { cat: "A", trigger: "“이건 공식 프로세스에 맞춰야 해.”", misread: "나를 제약하나?", reframe: "지속 가능성을 위한 조건일 수 있다." },
  { cat: "A", trigger: "“지금 customer-facing으로는 조심하자.”", misread: "나를 못 믿나?", reframe: "외부 노출 리스크 관리일 수 있다." },
  { cat: "A", trigger: "“이메일 먼저 나한테 보여줘.”", misread: "검열하나?", reframe: "톤 조율일 수 있다." },
  { cat: "A", trigger: "“이 내용은 너무 technical해.”", misread: "내가 설명 못한다는 뜻인가?", reframe: "청중 맞춤 요청일 수 있다." },
  { cat: "A", trigger: "“이건 너무 high-level이야.”", misread: "또 부족하다는 건가?", reframe: "필요한 detail level이 다를 수 있다." },
  { cat: "A", trigger: "“timeline 다시 정리해줘.”", misread: "내가 지연시키는 것처럼 보나?", reframe: "계획 가시화 요청일 수 있다." },
  { cat: "A", trigger: "“너 요즘 바빠 보여.”", misread: "성과가 안 보인다는 뜻인가?", reframe: "workload 체크일 수 있다." },
  { cat: "A", trigger: "“괜찮아?”", misread: "내가 흔들려 보이나?", reframe: "단순 배려일 수 있다." },
  { cat: "A", trigger: "“요즘 뭐 하고 있어?”", misread: "감시하나?", reframe: "status update 요청일 수 있다." },
  { cat: "A", trigger: "“다음 단계가 뭐야?”", misread: "지금까지 한 게 부족한가?", reframe: "action item 확인일 수 있다." },
  { cat: "A", trigger: "“이건 아직 공유하지 말자.”", misread: "숨기려 하나?", reframe: "타이밍 조절일 수 있다." },
  { cat: "A", trigger: "“A가 이 부분 더 잘 알아.”", misread: "나를 빼려 하나?", reframe: "subject expert 연결일 수 있다." },
  { cat: "A", trigger: "“그건 네 영역이 아니야.”", misread: "성장을 막나?", reframe: "ownership boundary일 수 있다." },
  { cat: "A", trigger: "“일단 작은 버전으로 가자.”", misread: "내 큰 그림을 못 보나?", reframe: "adoption 전략일 수 있다." },
  { cat: "A", trigger: "“너무 완벽하게 하려고 하지 마.”", misread: "대충 하라는 건가?", reframe: "과투입 방지일 수 있다." },
  { cat: "A", trigger: "“이건 나중에 평가하자.”", misread: "인정 미루기인가?", reframe: "결과가 쌓인 뒤 판단하려는 것일 수 있다." },
  { cat: "B", trigger: "“그거 AI가 만든 거야?”", misread: "내 실력을 무시하나?", reframe: "호기심 또는 농담일 수 있다." },
  { cat: "B", trigger: "“오, 이런 것도 했어?”", misread: "비꼬나?", reframe: "진짜 놀란 것일 수 있다." },
  { cat: "B", trigger: "“굳이 필요해?”", misread: "내 아이디어를 깎아내리나?", reframe: "사용성 질문일 수 있다." },
  { cat: "B", trigger: "“이미 비슷한 거 있지 않아?”", misread: "베낀 거라고 보나?", reframe: "중복 방지 질문일 수 있다." },
  { cat: "B", trigger: "“난 그냥 수동으로 할래.”", misread: "내 툴을 거부하나?", reframe: "습관 문제일 수 있다." },
  { cat: "B", trigger: "“나중에 볼게.”", misread: "관심 없다는 뜻인가?", reframe: "실제로 시간이 없을 수 있다." },
  { cat: "B", trigger: "“이거 어떻게 쓰는 거야?”", misread: "문서가 부족하다는 비판인가?", reframe: "온보딩 기회일 수 있다." },
  { cat: "B", trigger: "“에러 나는데?”", misread: "내 툴이 별로라는 뜻인가?", reframe: "버그 리포트일 수 있다." },
  { cat: "B", trigger: "“이건 내 방식이랑 달라.”", misread: "나를 틀렸다고 보나?", reframe: "워크플로우 차이일 수 있다." },
  { cat: "B", trigger: "“나는 예전 방식이 편해.”", misread: "변화 거부인가?", reframe: "익숙함의 문제일 수 있다." },
  { cat: "B", trigger: "“그거 공식 툴이야?”", misread: "불법/비공식이라고 의심하나?", reframe: "governance 확인일 수 있다." },
  { cat: "B", trigger: "“누가 승인했어?”", misread: "나를 공격하나?", reframe: "사용 범위 확인일 수 있다." },
  { cat: "B", trigger: "“코드 공유 가능해?”", misread: "내 것을 뺏으려 하나?", reframe: "협업 의도일 수 있다." },
  { cat: "B", trigger: "“문서 있어?”", misread: "준비 부족 지적인가?", reframe: "확산을 위한 요청일 수 있다." },
  { cat: "B", trigger: "“이거 maintain 누가 해?”", misread: "네가 감당 못한다는 뜻인가?", reframe: "장기 운영 질문일 수 있다." },
  { cat: "B", trigger: "“나도 비슷한 거 생각했는데.”", misread: "공을 가져가려 하나?", reframe: "단순 공감일 수 있다." },
  { cat: "B", trigger: "“이거 customer한테 보여줘도 돼?”", misread: "나를 시험하나?", reframe: "확산 가능성 검토일 수 있다." },
  { cat: "B", trigger: "“대단하네.”", misread: "비꼬는 건가?", reframe: "진짜 칭찬일 수 있다." },
  { cat: "B", trigger: "“너 요즘 코딩 많이 하네.”", misread: "본업 안 한다는 뜻인가?", reframe: "관찰일 수 있다." },
  { cat: "B", trigger: "“이거 언제 만들었어?”", misread: "근무시간 의심인가?", reframe: "제작 배경 궁금증일 수 있다." },
  { cat: "B", trigger: "“너 혼자 만든 거야?”", misread: "못 믿나?", reframe: "놀람일 수 있다." },
  { cat: "B", trigger: "“와, 이거 꽤 복잡한데?”", misread: "문제 많다는 뜻인가?", reframe: "기술적 인정일 수 있다." },
  { cat: "B", trigger: "“좀 천천히 설명해줘.”", misread: "내가 설명을 못했나?", reframe: "상대가 따라오는 속도 문제일 수 있다." },
  { cat: "B", trigger: "“나는 잘 모르겠어.”", misread: "관심 없다는 뜻인가?", reframe: "도메인 차이일 수 있다." },
  { cat: "B", trigger: "“이거 나한테는 필요 없을 듯.”", misread: "내 가치가 부정당했나?", reframe: "사용자군이 다른 것일 수 있다." },
  { cat: "B", trigger: "“너무 기능이 많아.”", misread: "과하다는 비판인가?", reframe: "UX 단순화 힌트일 수 있다." },
  { cat: "B", trigger: "“이건 나중에 쓰면 좋겠다.”", misread: "지금은 별로라는 뜻인가?", reframe: "타이밍 문제일 수 있다." },
  { cat: "B", trigger: "“이거 고객 요구사항이야?”", misread: "개인 취미로 보나?", reframe: "business need 확인일 수 있다." },
  { cat: "B", trigger: "“재밌네.”", misread: "가볍게 보나?", reframe: "긍정적 관심일 수 있다." },
  { cat: "B", trigger: "“한번 demo 해봐.”", misread: "공격 준비인가?", reframe: "기회일 수 있다." },
  { cat: "B", trigger: "“이 부분은 내가 봐줄게.”", misread: "내가 부족하다고 생각하나?", reframe: "협업 제안일 수 있다." },
  { cat: "B", trigger: "“내가 알던 거랑 다른데?”", misread: "나를 틀렸다고 보나?", reframe: "정보 차이일 수 있다." },
  { cat: "B", trigger: "“source가 뭐야?”", misread: "못 믿겠다는 뜻인가?", reframe: "검증 습관일 수 있다." },
  { cat: "B", trigger: "“이거 고객한테 말하면 위험하지 않아?”", misread: "막으려는 건가?", reframe: "리스크 인식일 수 있다." },
  { cat: "B", trigger: "“나중에 팀 미팅에서 말하자.”", misread: "지금 피하려 하나?", reframe: "더 큰 청중을 만들려는 것일 수 있다." },
  { cat: "B", trigger: "“그건 manager랑 얘기했어?”", misread: "나를 통제하려 하나?", reframe: "escalation path 확인일 수 있다." },
  { cat: "B", trigger: "“이거 네가 계속 support해야 해?”", misread: "부담 주나?", reframe: "운영 모델 질문일 수 있다." },
  { cat: "B", trigger: "“이거 버전 관리 돼?”", misread: "불신인가?", reframe: "툴 성숙도 질문일 수 있다." },
  { cat: "B", trigger: "“UI가 좀 낯설어.”", misread: "별로라는 뜻인가?", reframe: "개선 포인트일 수 있다." },
  { cat: "B", trigger: "“좋은데, 조금 헷갈려.”", misread: "실패인가?", reframe: "사용성 개선 기회일 수 있다." },
  { cat: "C", trigger: "“Can you provide more details?”", misread: "내 설명이 부족하다는 공격인가?", reframe: "추가 정보 요청이다." },
  { cat: "C", trigger: "“What is the evidence?”", misread: "나를 의심하나?", reframe: "기술 판단의 근거 요청이다." },
  { cat: "C", trigger: "“How did you validate this?”", misread: "내가 대충 했다고 보나?", reframe: "검증 절차 확인이다." },
  { cat: "C", trigger: "“Is this reproducible?”", misread: "내 결과를 못 믿나?", reframe: "제품화 가능성 확인이다." },
  { cat: "C", trigger: "“What is the scope?”", misread: "제한하려 하나?", reframe: "적용 범위 정리다." },
  { cat: "C", trigger: "“What is the limitation?”", misread: "약점 캐내기인가?", reframe: "리스크 관리다." },
  { cat: "C", trigger: "“Can you compare with current method?”", misread: "새 툴 부정인가?", reframe: "impact 정량화 기회다." },
  { cat: "C", trigger: "“Who are the users?”", misread: "관심 없다는 뜻인가?", reframe: "adoption 대상 확인이다." },
  { cat: "C", trigger: "“What problem are you solving?”", misread: "가치 없다는 뜻인가?", reframe: "problem statement 요구다." },
  { cat: "C", trigger: "“Is this scalable?”", misread: "지금 것은 작다는 비판인가?", reframe: "확장성 질문이다." },
  { cat: "C", trigger: "“Can you send a concise summary?”", misread: "내 detail이 쓸모없나?", reframe: "decision maker용 요약이다." },
  { cat: "C", trigger: "“Let’s align internally first.”", misread: "막는 건가?", reframe: "메시지 일관성 확보일 수 있다." },
  { cat: "C", trigger: "“We need to check compliance.”", misread: "내가 규정 위반했나?", reframe: "공식화 전 절차다." },
  { cat: "C", trigger: "“This may overlap with existing tools.”", misread: "내 작업이 불필요한가?", reframe: "통합 가능성 검토다." },
  { cat: "C", trigger: "“Who owns this?”", misread: "공 뺏기인가?", reframe: "책임 구조 확인이다." },
  { cat: "C", trigger: "“Can this be maintained?”", misread: "내가 감당 못한다고 보나?", reframe: "장기 운영성 질문이다." },
  { cat: "C", trigger: "“Do you have documentation?”", misread: "준비 부족 지적?", reframe: "확산을 위한 필수 자료다." },
  { cat: "C", trigger: "“Can you share the architecture?”", misread: "코드를 빼앗기나?", reframe: "이해와 검토 목적일 수 있다." },
  { cat: "C", trigger: "“What are the dependencies?”", misread: "약점 찾기인가?", reframe: "운영 리스크 확인이다." },
  { cat: "C", trigger: "“What is the failure mode?”", misread: "내 툴이 위험하다는 뜻인가?", reframe: "안전 설계 질문이다." },
  { cat: "C", trigger: "“This is interesting.”", misread: "애매하게 넘기나?", reframe: "초기 긍정 신호일 수 있다." },
  { cat: "C", trigger: "“Let us think about it.”", misread: "거절인가?", reframe: "검토 시간이 필요한 것일 수 있다." },
  { cat: "C", trigger: "“Not now.”", misread: "가치 없다는 뜻인가?", reframe: "우선순위 문제일 수 있다." },
  { cat: "C", trigger: "“Can we revisit later?”", misread: "묻어두려 하나?", reframe: "타이밍 조정일 수 있다." },
  { cat: "C", trigger: "“We need customer input.”", misread: "내 판단을 안 믿나?", reframe: "외부 validation 필요다." },
  { cat: "C", trigger: "“This is not standard yet.”", misread: "하지 말라는 뜻인가?", reframe: "표준화 전 단계라는 뜻이다." },
  { cat: "C", trigger: "“Can you make it simpler?”", misread: "내 설계가 별로인가?", reframe: "사용자 확산을 위한 요청이다." },
  { cat: "C", trigger: "“What is the minimum viable version?”", misread: "큰 그림을 무시하나?", reframe: "adoption entry point를 찾는 것이다." },
  { cat: "C", trigger: "“Can you separate personal tool and official process?”", misread: "나를 의심하나?", reframe: "governance 구분이다." },
  { cat: "C", trigger: "“We should avoid custom scripts.”", misread: "내 코딩을 막나?", reframe: "유지보수 리스크 관점이다." },
  { cat: "D", trigger: "“When can we get the result?”", misread: "나를 압박하나?", reframe: "일정 확인이다." },
  { cat: "D", trigger: "“Why is this delayed?”", misread: "내 책임으로 몰아가나?", reframe: "원인 파악 요청이다." },
  { cat: "D", trigger: "“Is there any improvement?”", misread: "내 분석을 의심하나?", reframe: "결과 판단 기준을 묻는 것이다." },
  { cat: "D", trigger: "“Can you show the data?”", misread: "못 믿는다는 건가?", reframe: "객관적 근거 요청이다." },
  { cat: "D", trigger: "“This does not look improved.”", misread: "내 노력이 부정당했나?", reframe: "고객 시야에서는 아직 부족할 수 있다." },
  { cat: "D", trigger: "“We need more evidence.”", misread: "나를 공격하나?", reframe: "의사결정에 필요한 자료가 더 필요한 것이다." },
  { cat: "D", trigger: "“Can ASML confirm?”", misread: "나 개인을 못 믿나?", reframe: "공식 답변이 필요한 상황이다." },
  { cat: "D", trigger: "“Who is responsible?”", misread: "나를 몰아가나?", reframe: "ownership clarification이다." },
  { cat: "D", trigger: "“Can we escalate?”", misread: "내가 실패했나?", reframe: "빠른 해결을 위한 경로다." },
  { cat: "D", trigger: "“This is urgent.”", misread: "나를 몰아붙이나?", reframe: "고객 일정상 중요하다는 의미다." },
  { cat: "D", trigger: "“We expected better.”", misread: "내가 실망시켰나?", reframe: "기대치 조정이 필요하다." },
  { cat: "D", trigger: "“Can you explain in simple terms?”", misread: "내가 복잡하게 말했나?", reframe: "청중 맞춤 요청이다." },
  { cat: "D", trigger: "“We already tried that.”", misread: "내 제안을 무시하나?", reframe: "과거 시도 정보 제공이다." },
  { cat: "D", trigger: "“That will not work.”", misread: "나를 깎아내리나?", reframe: "고객 경험 기반 우려다." },
  { cat: "D", trigger: "“Can you propose next steps?”", misread: "내가 준비 안 됐다고 보나?", reframe: "action plan 요청이다." },
  { cat: "D", trigger: "“We need a meeting.”", misread: "문제 커졌나?", reframe: "alignment가 필요한 상황일 수 있다." },
  { cat: "D", trigger: "“Can you send a written summary?”", misread: "말로는 못 믿겠나?", reframe: "기록용 요청이다." },
  { cat: "D", trigger: "“This is not clear.”", misread: "내 설명이 형편없나?", reframe: "메시지 구조 개선 요청이다." },
  { cat: "D", trigger: "“Can you include timeline?”", misread: "지연 의심인가?", reframe: "planning clarity 요구다." },
  { cat: "D", trigger: "“What is the risk?”", misread: "내가 위험한 제안을 했나?", reframe: "결정 전 risk assessment다." },
  { cat: "E", trigger: "“?”만 보냄", misread: "화났나?", reframe: "빠른 확인 신호일 수 있다." },
  { cat: "E", trigger: "“Please advise.”", misread: "책임 떠넘기나?", reframe: "의견 요청일 수 있다." },
  { cat: "E", trigger: "“Any update?”", misread: "독촉인가?", reframe: "상태 확인일 수 있다." },
  { cat: "E", trigger: "“Following up.”", misread: "압박인가?", reframe: "놓치지 않기 위한 리마인더다." },
  { cat: "E", trigger: "“Let me know.”", misread: "무심한가?", reframe: "일반적인 업무 표현이다." },
  { cat: "E", trigger: "“Thanks.”만 보냄", misread: "차갑다", reframe: "간단히 끝낸 것일 수 있다." },
  { cat: "E", trigger: "“OK.”만 보냄", misread: "불쾌한가?", reframe: "단순 승인일 수 있다." },
  { cat: "E", trigger: "“Noted.”", misread: "감정 없는 벽인가?", reframe: "기록했다는 뜻이다." },
  { cat: "E", trigger: "“Fine.”", misread: "비꼬나?", reframe: "맥락 없이는 판단 불가다." },
  { cat: "E", trigger: "“Sure.”", misread: "마지못해 하나?", reframe: "그냥 동의일 수 있다." },
  { cat: "E", trigger: "“Let’s discuss.”", misread: "문제 제기인가?", reframe: "말로 정리하려는 것일 수 있다." },
  { cat: "E", trigger: "“Can you clarify?”", misread: "내가 불분명했나?", reframe: "정보 보완 요청이다." },
  { cat: "E", trigger: "“I’m confused.”", misread: "내 설명이 엉망인가?", reframe: "상대가 맥락을 놓쳤을 수 있다." },
  { cat: "E", trigger: "“I don’t follow.”", misread: "내가 못 설명했나?", reframe: "단계별 설명이 필요한 것일 수 있다." },
  { cat: "E", trigger: "“This is different from my understanding.”", misread: "충돌인가?", reframe: "정보 alignment 필요다." },
  { cat: "E", trigger: "“Correct me if I’m wrong.”", misread: "방어적 공격인가?", reframe: "정중한 확인 표현이다." },
  { cat: "E", trigger: "“Just checking.”", misread: "감시인가?", reframe: "가벼운 확인이다." },
  { cat: "E", trigger: "“Can you resend?”", misread: "무시했나?", reframe: "파일을 못 찾았을 수 있다." },
  { cat: "E", trigger: "“I missed this.”", misread: "일부러 안 봤나?", reframe: "진짜 놓쳤을 수 있다." },
  { cat: "E", trigger: "“Sorry, busy.”", misread: "나를 우선순위에서 뺐나?", reframe: "실제 일정 문제일 수 있다." },
  { cat: "F", trigger: "누군가 내 말 중간에 끊음", misread: "무시당했다", reframe: "시간 관리일 수 있다." },
  { cat: "F", trigger: "질문이 많이 들어옴", misread: "공격받는다", reframe: "관심이 있다는 뜻일 수 있다." },
  { cat: "F", trigger: "아무도 질문 안 함", misread: "관심 없다", reframe: "이해했거나 시간이 없을 수 있다." },
  { cat: "F", trigger: "카메라 꺼짐", misread: "무례하다", reframe: "회사 문화나 환경 문제일 수 있다." },
  { cat: "F", trigger: "누군가 한숨 쉼", misread: "내 발표가 별로인가", reframe: "피곤한 것일 수 있다." },
  { cat: "F", trigger: "채팅이 조용함", misread: "반응이 나쁘다", reframe: "다들 듣고 있을 수 있다." },
  { cat: "F", trigger: "한 사람이 반대함", misread: "전체가 반대한다", reframe: "한 의견일 뿐이다." },
  { cat: "F", trigger: "매니저가 대신 답함", misread: "내 발언권을 뺏었다", reframe: "공식 톤을 조절한 것일 수 있다." },
  { cat: "F", trigger: "누군가 “시간 없으니 넘어가자”", misread: "내 파트를 무시했다", reframe: "agenda 관리일 수 있다." },
  { cat: "F", trigger: "follow-up action이 나에게 옴", misread: "나만 떠맡겼다", reframe: "네가 가장 context를 갖고 있기 때문일 수 있다." },
  { cat: "F", trigger: "회의 후 피드백 없음", misread: "실패했다", reframe: "문제 없어서 조용한 것일 수 있다." },
  { cat: "F", trigger: "회의 후 질문이 옴", misread: "발표가 부족했다", reframe: "더 깊이 관심이 생겼을 수 있다." },
  { cat: "F", trigger: "누군가 내 자료를 다시 설명함", misread: "내 설명을 못 믿는다", reframe: "청중에게 재프레이밍한 것일 수 있다." },
  { cat: "F", trigger: "슬라이드 순서 바꾸자고 함", misread: "내 구조가 틀렸다", reframe: "메시지 흐름 개선일 수 있다." },
  { cat: "F", trigger: "detail 줄이자고 함", misread: "내 노력이 무시됐다", reframe: "청중이 executive level일 수 있다." },
  { cat: "F", trigger: "detail 더 넣자고 함", misread: "내 자료가 빈약하다", reframe: "기술 검토용 버전이 필요한 것이다." },
  { cat: "F", trigger: "회의 초대에서 빠짐", misread: "배제됐다", reframe: "이번 agenda와 직접 관련이 없을 수 있다." },
  { cat: "F", trigger: "갑자기 회의 초대됨", misread: "공격받나?", reframe: "네 input이 필요해졌을 수 있다." },
  { cat: "F", trigger: "다른 senior가 참석함", misread: "나를 감시하나?", reframe: "subject coverage 목적일 수 있다." },
  { cat: "F", trigger: "회의 제목이 애매함", misread: "함정인가?", reframe: "작성자가 대충 썼을 수 있다." },
  { cat: "G", trigger: "칭찬이 없음", misread: "인정받지 못했다", reframe: "조용히 신뢰가 쌓일 수 있다." },
  { cat: "G", trigger: "누가 내 툴을 언급 안 함", misread: "공을 뺏겼다", reframe: "아직 공식화 전일 수 있다." },
  { cat: "G", trigger: "다른 사람이 발표함", misread: "내가 지워졌다", reframe: "조직 메시지 역할일 수 있다." },
  { cat: "G", trigger: "“team effort”라고 함", misread: "내 기여 희석인가?", reframe: "조직 언어일 수 있다." },
  { cat: "G", trigger: "manager가 내 성과를 고객에게 말 안 함", misread: "숨기나?", reframe: "타이밍 조절일 수 있다." },
  { cat: "G", trigger: "동료가 내 아이디어를 반복함", misread: "훔쳤나?", reframe: "이해해서 재표현한 것일 수 있다." },
  { cat: "G", trigger: "내 이름이 빠짐", misread: "고의 배제인가?", reframe: "문서 작성 실수일 수 있다." },
  { cat: "G", trigger: "피드백이 늦음", misread: "관심 없다", reframe: "바쁜 일정 때문일 수 있다." },
  { cat: "G", trigger: "승인이 늦음", misread: "막고 있다", reframe: "절차가 느릴 수 있다." },
  { cat: "G", trigger: "사용자가 늘지 않음", misread: "가치 없다", reframe: "adoption은 시간이 걸린다." },
  { cat: "G", trigger: "일부만 사용함", misread: "전체 툴이 실패했다", reframe: "작은 기능부터 신뢰가 생기는 것이다." },
  { cat: "G", trigger: "질문만 받고 칭찬 없음", misread: "인정 안 한다", reframe: "검토 단계일 수 있다." },
  { cat: "G", trigger: "“interesting”만 들음", misread: "애매한 거절이다", reframe: "초기 호기심 표현일 수 있다." },
  { cat: "G", trigger: "“good start”", misread: "아직 별로라는 뜻인가", reframe: "발전 가능성 인정일 수 있다." },
  { cat: "G", trigger: "“prototype”이라고 부름", misread: "장난감 취급인가", reframe: "제품화 전 단계라는 뜻이다." },
  { cat: "G", trigger: "“personal project”라고 함", misread: "공식 가치 없나", reframe: "현재 소유 구조를 말한 것일 수 있다." },
  { cat: "G", trigger: "“tool”이라고만 함", misread: "내 제품 비전을 축소하나", reframe: "업무에서는 보통 그렇게 부른다." },
  { cat: "G", trigger: "누가 내 도움을 당연하게 여김", misread: "나를 이용하나", reframe: "네 기여가 유용해진 신호일 수 있다." },
  { cat: "G", trigger: "“Thanks for helping”", misread: "네가 owner가 아니라는 뜻인가", reframe: "상황별 감사 표현이다." },
  { cat: "G", trigger: "“Can you support this?”", misread: "잡일 떠넘기나", reframe: "신뢰받는 담당으로 보일 수 있다." },
  { cat: "H", trigger: "“아직 공부 중이지?”", misread: "나를 초보 취급하나", reframe: "성장 과정을 인정하는 말일 수 있다." },
  { cat: "H", trigger: "“이건 advanced topic이야.”", misread: "넌 아직 못해라는 뜻인가", reframe: "난이도 안내일 수 있다." },
  { cat: "H", trigger: "“기본부터 다시 보자.”", misread: "내가 기초도 모른다는 뜻인가", reframe: "안정적 학습 전략일 수 있다." },
  { cat: "H", trigger: "“너무 빨리 가는 것 같아.”", misread: "내가 무리한다는 비판인가", reframe: "소화 속도 걱정일 수 있다." },
  { cat: "H", trigger: "“천천히 해.”", misread: "성과 낮추라는 뜻인가", reframe: "지속 가능성을 위한 조언일 수 있다." },
  { cat: "H", trigger: "“이건 나중에 이해될 거야.”", misread: "지금 넌 못 알아듣는다는 뜻인가", reframe: "학습 순서의 문제다." },
  { cat: "H", trigger: "에러가 남", misread: "나는 재능이 없다", reframe: "환경/문법/의존성 문제일 수 있다." },
  { cat: "H", trigger: "모듈 설치 실패", misread: "개발은 나랑 안 맞다", reframe: "개발자의 일상이다." },
  { cat: "H", trigger: "이해가 늦음", misread: "머리가 나쁘다", reframe: "새로운 개념은 반복이 필요하다." },
  { cat: "H", trigger: "같은 질문 반복", misread: "나는 못 배운다", reframe: "깊게 배우는 과정이다." },
  { cat: "H", trigger: "Python은 괜찮은데 JS가 헷갈림", misread: "난 개발자 타입이 아니다", reframe: "언어 모델이 다른 것이다." },
  { cat: "H", trigger: "JS가 재미있음", misread: "본업에서 도망치는 건가", reframe: "학습 동기가 생긴 것이다." },
  { cat: "H", trigger: "클래스를 어렵게 느낌", misread: "OOP 재능 없다", reframe: "추상화는 원래 늦게 잡힌다." },
  { cat: "H", trigger: "dict/JSON 구조에 감동함", misread: "너무 늦게 알았다", reframe: "이제 연결되기 시작한 것이다." },
  { cat: "H", trigger: "DOM 이해가 오래 걸림", misread: "난 웹을 못한다", reframe: "데이터 구조 관점이 열리는 중이다." },
  { cat: "H", trigger: "Tauri 빌드 실패", misread: "프로젝트 망했다", reframe: "환경 세팅은 별도 문제다." },
  { cat: "H", trigger: "Visual Studio linker 에러", misread: "내 코드 문제다", reframe: "빌드 도구 문제일 수 있다." },
  { cat: "H", trigger: "pandas 에러", misread: "데이터 분석이 안 맞다", reframe: "입력/환경 문제일 수 있다." },
  { cat: "H", trigger: "regex가 헷갈림", misread: "기초 부족이다", reframe: "regex는 모두가 헷갈린다." },
  { cat: "H", trigger: "모델링 개념이 넓게 느껴짐", misread: "내가 이상하게 생각하나", reframe: "좋은 추상화 능력이다." },
  { cat: "I", trigger: "누군가 더 경력 많음", misread: "난 경쟁력 없다", reframe: "경험의 종류가 다르다." },
  { cat: "I", trigger: "누군가 발표를 잘함", misread: "난 부족하다", reframe: "발표와 문제 해결은 다른 능력이다." },
  { cat: "I", trigger: "누군가 정치적으로 잘 움직임", misread: "내가 뒤처졌다", reframe: "너는 기술과 실행력으로 쌓고 있다." },
  { cat: "I", trigger: "누군가 인정 빨리 받음", misread: "내 노력은 헛되다", reframe: "가시화 속도는 사람마다 다르다." },
  { cat: "I", trigger: "누군가 말로 포장 잘함", misread: "내가 손해 본다", reframe: "네 강점은 실제 결과물이다." },
  { cat: "I", trigger: "동료가 자신감 있어 보임", misread: "내가 작아진다", reframe: "겉모습과 실력은 다르다." },
  { cat: "I", trigger: "누군가 내 위에 있음", misread: "나는 늦었다", reframe: "방향성이 더 중요하다." },
  { cat: "I", trigger: "나보다 어린 사람이 잘함", misread: "난 늦었다", reframe: "축적된 도메인 경험은 별도 자산이다." },
  { cat: "I", trigger: "AI/LLM을 잘 쓰는 사람 봄", misread: "나도 금방 대체될까", reframe: "도메인+툴 활용자가 더 강해진다." },
  { cat: "I", trigger: "개발자 출신과 비교함", misread: "난 비전공자다", reframe: "현장 문제를 아는 builder라는 강점이 있다." },
  { cat: "I", trigger: "데이터 사이언티스트와 비교함", misread: "난 애매하다", reframe: "너는 장비/공정/데이터를 연결한다." },
  { cat: "I", trigger: "고객 앞에서 유창한 사람 봄", misread: "난 부족하다", reframe: "정확함과 신뢰도도 중요하다." },
  { cat: "I", trigger: "회사에서 낮은 평가 기억", misread: "난 원래 부족하다", reframe: "과거 평가는 전체 정체성이 아니다." },
  { cat: "I", trigger: "무시했던 동료가 떠오름", misread: "증명해야 한다", reframe: "이미 네 성장으로 복수는 끝났다." },
  { cat: "I", trigger: "남이 쉬워 보임", misread: "나는 왜 힘들지", reframe: "내부 전투는 밖에서 안 보인다." },
  { cat: "I", trigger: "포트폴리오가 부족해 보임", misread: "아직 아무것도 아니다", reframe: "이미 여러 도구를 만들었다." },
  { cat: "I", trigger: "“진짜 개발자” 기준 생각", misread: "나는 가짜다", reframe: "문제를 해결하면 개발이다." },
  { cat: "I", trigger: "“전문가” 기준 생각", misread: "나는 멀었다", reframe: "전문가도 계속 모른다." },
  { cat: "I", trigger: "지식의 빙산을 느낌", misread: "난 작다", reframe: "진짜 배움의 시작이다." },
  { cat: "I", trigger: "공부할 게 많음", misread: "압도된다", reframe: "roadmap이 필요한 것이다." },
  { cat: "J", trigger: "누가 날 의심하는 듯함", misread: "바로 반박해야 한다", reframe: "먼저 질문으로 분리한다." },
  { cat: "J", trigger: "억울한 말 들음", misread: "즉시 정정해야 한다", reframe: "기록 후 차분히 답한다." },
  { cat: "J", trigger: "비꼬는 듯한 톤", misread: "공격이다", reframe: "톤보다 사실을 본다." },
  { cat: "J", trigger: "불공정한 지시", misread: "싸워야 한다", reframe: "범위와 우선순위를 문서화한다." },
  { cat: "J", trigger: "누가 내 공을 흐림", misread: "방어해야 한다", reframe: "조용히 evidence trail을 남긴다." },
  { cat: "J", trigger: "내 설명을 안 들음", misread: "무시다", reframe: "상대의 이해 수준이 다를 수 있다." },
  { cat: "J", trigger: "같은 질문 반복", misread: "나를 괴롭힌다", reframe: "documentation gap일 수 있다." },
  { cat: "J", trigger: "갑자기 리뷰 요청", misread: "함정이다", reframe: "준비된 사실만 가져간다." },
  { cat: "J", trigger: "상대가 표정 안 좋음", misread: "나 때문인가", reframe: "그 사람 컨디션일 수 있다." },
  { cat: "J", trigger: "상대가 짧게 답함", misread: "나를 싫어한다", reframe: "커뮤니케이션 스타일일 수 있다." },
  { cat: "J", trigger: "회의가 길어짐", misread: "내 시간이 빼앗긴다", reframe: "agenda reset 요청 가능하다." },
  { cat: "J", trigger: "irrelevant talk 많음", misread: "사람들이 무능하다", reframe: "회의 문화 문제일 수 있다." },
  { cat: "J", trigger: "무례한 질문", misread: "나를 낮춘다", reframe: "질문의 질이 낮을 뿐 내 가치와 별개다." },
  { cat: "J", trigger: "상대가 몰라도 아는 척함", misread: "화남", reframe: "네가 차분히 기준을 잡으면 된다." },
  { cat: "J", trigger: "manager가 애매하게 말함", misread: "숨은 의도가 있다", reframe: "애매한 사람일 수 있다." },
  { cat: "J", trigger: "나만 일 많이 함", misread: "이용당한다", reframe: "visibility와 boundary가 필요하다." },
  { cat: "J", trigger: "내가 빨리 해결함", misread: "또 당연해질까 걱정", reframe: "속도보다 전달 방식을 조절한다." },
  { cat: "J", trigger: "답장이 늦음", misread: "나를 무시한다", reframe: "상대 일정일 수 있다." },
  { cat: "J", trigger: "거절당함", misread: "나 자체가 거절당했다", reframe: "제안의 타이밍이 거절된 것이다." },
  { cat: "J", trigger: "수정 요청 받음", misread: "실패했다", reframe: "협업 과정이다." },
  { cat: "K", trigger: "업체가 답 늦음", misread: "나를 무시한다", reframe: "일정이 밀렸을 수 있다." },
  { cat: "K", trigger: "HOA가 conditional approval 줌", misread: "또 문제 삼나", reframe: "승인 과정의 조건일 수 있다." },
  { cat: "K", trigger: "추가 수정 요구", misread: "내 집을 괴롭히나", reframe: "규정 적용일 수 있다." },
  { cat: "K", trigger: "contractor가 바로 못 옴", misread: "책임감 없다", reframe: "스케줄 문제일 수 있다." },
  { cat: "K", trigger: "비용이 예상보다 큼", misread: "바가지인가", reframe: "범위 차이 확인이 필요하다." },
  { cat: "K", trigger: "pest control이 full charge함", misread: "일부러 속였다", reframe: "서비스 코드 오해일 수 있다." },
  { cat: "K", trigger: "reservice인데 비용 청구", misread: "나를 이용했다", reframe: "기록 기반으로 정정 요청하면 된다." },
  { cat: "K", trigger: "업체가 “regular service”라 함", misread: "내 말을 안 들었다", reframe: "사전 안내 누락일 수 있다." },
  { cat: "K", trigger: "집에 없을 때 서비스함", misread: "배려 없다", reframe: "scheduling communication gap이다." },
  { cat: "K", trigger: "HOA 답장 늦음", misread: "불리하게 처리하나", reframe: "담당자 queue 문제일 수 있다." },
  { cat: "L", trigger: "아내가 앱 개선 요청", misread: "내 결과물이 부족했나", reframe: "실제 사용자 피드백이다." },
  { cat: "L", trigger: "아내가 현실적 조언", misread: "내 꿈을 막나", reframe: "생활 균형을 보는 것이다." },
  { cat: "L", trigger: "집안일 지적", misread: "나는 못하는 남편인가", reframe: "역할 조율 문제다." },
  { cat: "L", trigger: "육아 관련 의견 차이", misread: "내가 부족한 아빠인가", reframe: "서로 배우는 과정이다." },
  { cat: "L", trigger: "아기가 힘들어함", misread: "내가 잘못했나", reframe: "아기는 원래 예측 불가다." },
  { cat: "L", trigger: "가족 때문에 공부 시간 줄어듦", misread: "성장 멈추나", reframe: "장기 리듬 조정이다." },
  { cat: "L", trigger: "피곤해서 예민함", misread: "내가 약하다", reframe: "회복이 필요한 신호다." },
  { cat: "L", trigger: "아내가 조용함", misread: "실망했나", reframe: "단순히 피곤할 수 있다." },
  { cat: "L", trigger: "부탁을 받음", misread: "내 시간이 또 뺏긴다", reframe: "사랑하는 사람의 실제 필요다." },
  { cat: "L", trigger: "계획이 틀어짐", misread: "하루 망했다", reframe: "최소 단위로 재시작하면 된다." },
  { cat: "M", trigger: "눈이 뿌옇다", misread: "큰 병인가", reframe: "검진 필요하지만 피로/건조도 가능하다." },
  { cat: "M", trigger: "가까운 게 안 보임", misread: "노화가 왔다", reframe: "자연스러운 변화일 수 있다." },
  { cat: "M", trigger: "눈부심 있음", misread: "심각한 문제인가", reframe: "확인은 필요하지만 단정하지 않는다." },
  { cat: "M", trigger: "오후 집중력 저하", misread: "의지가 약하다", reframe: "바이오리듬 패턴일 수 있다." },
  { cat: "M", trigger: "허리 통증", misread: "나는 망가졌다", reframe: "관리와 조절이 필요하다." },
  { cat: "M", trigger: "피곤함", misread: "게으르다", reframe: "회복 부족일 수 있다." },
  { cat: "M", trigger: "머리가 멍함", misread: "능력 저하인가", reframe: "수면/스트레스 영향일 수 있다." },
  { cat: "M", trigger: "말이 많아짐", misread: "ADHD인가", reframe: "진단보다 상황 패턴을 본다." },
  { cat: "M", trigger: "혼잣말함", misread: "이상한가", reframe: "사고 정리 방식일 수 있다." },
  { cat: "M", trigger: "감정 올라옴", misread: "나는 아직 약하다", reframe: "감지를 잘하고 있다는 신호다." },
  { cat: "N", trigger: "오전에만 잘됨", misread: "반쪽짜리 사람인가", reframe: "최고의 시간대를 찾은 것이다." },
  { cat: "N", trigger: "오후에 무너짐", misread: "실패다", reframe: "낮은 에너지용 작업을 배치하면 된다." },
  { cat: "N", trigger: "하루 공부 못함", misread: "퇴보했다", reframe: "한 번 빠진 것뿐이다." },
  { cat: "N", trigger: "계획보다 적게 함", misread: "망했다", reframe: "유지가 더 중요하다." },
  { cat: "N", trigger: "너무 많은 프로젝트", misread: "산만하다", reframe: "시스템화하면 자산이다." },
  { cat: "N", trigger: "한 프로젝트 중단", misread: "끈기 없다", reframe: "우선순위 재조정일 수 있다." },
  { cat: "N", trigger: "새 아이디어 생김", misread: "또 도망가나", reframe: "idea bank에 넣으면 된다." },
  { cat: "N", trigger: "코딩이 즐거움", misread: "현실 회피인가", reframe: "건강한 몰입일 수 있다." },
  { cat: "N", trigger: "공부가 불안 완화 수단", misread: "문제인가", reframe: "균형만 잡으면 강점이다." },
  { cat: "N", trigger: "쉬면 불안함", misread: "뒤처진다", reframe: "회복도 성장의 일부다." },
  { cat: "O", trigger: "사용자가 기능 요청", misread: "기존 기능이 부족했나", reframe: "제품이 살아 있다는 뜻이다." },
  { cat: "O", trigger: "버그 발견", misread: "실패다", reframe: "실제 사용이 시작됐다는 뜻이다." },
  { cat: "O", trigger: "UI 지적", misread: "툴이 별로다", reframe: "adoption을 위한 정보다." },
  { cat: "O", trigger: "기능이 많다는 말", misread: "과욕이다", reframe: "progressive disclosure가 필요하다." },
  { cat: "O", trigger: "기능이 적다는 말", misread: "부족하다", reframe: "MVP와 full version 차이다." },
  { cat: "O", trigger: "문서 요청", misread: "불신이다", reframe: "제품화 필수 단계다." },
  { cat: "O", trigger: "배포 전 승인 대기", misread: "막혔다", reframe: "release process다." },
  { cat: "O", trigger: "TestFlight 대기", misread: "실패인가", reframe: "플랫폼 절차다." },
  { cat: "O", trigger: "아이콘이 마음에 안 듦", misread: "감각이 없다", reframe: "디자인 iteration이다." },
  { cat: "O", trigger: "검은색 border가 싫음", misread: "내가 까다로운가", reframe: "brand preference가 명확한 것이다." },
  { cat: "O", trigger: "RouteStar가 작아 보임", misread: "별거 아닌 앱인가", reframe: "route optimizer는 좋은 제품 연습이다." },
  { cat: "O", trigger: "Baby Tracker 개선", misread: "가족용 장난감인가", reframe: "실제 사용자 문제 해결이다." },
  { cat: "O", trigger: "SeedLog 구조 변경", misread: "계속 갈아엎는다", reframe: "더 맞는 운영체계를 찾는 중이다." },
  { cat: "O", trigger: "MindDebugger 개발", misread: "내가 문제가 많다는 뜻인가", reframe: "자기조절 도구를 만드는 것이다." },
  { cat: "O", trigger: "StructDiff 일반화", misread: "너무 큰 프로젝트인가", reframe: "도메인 지식을 제품화하는 과정이다." },
  { cat: "O", trigger: "XML compare 확장", misread: "회사에서 금지될까", reframe: "개인 학습/내부 효율화 경계가 중요하다." },
  { cat: "O", trigger: "PDF extractor 개발", misread: "단순 자동화인가", reframe: "지식 검색 시스템의 시작이다." },
  { cat: "O", trigger: "Codex 만들기", misread: "정리병인가", reframe: "지식 자산화다." },
  { cat: "O", trigger: "프로젝트가 많음", misread: "산만하다", reframe: "pipeline으로 관리하면 portfolio다." },
  { cat: "O", trigger: "dashboard 만들기", misread: "겉멋인가", reframe: "흐름을 보려는 운영 도구다." },
  { cat: "P", trigger: "누군가 친한 사람끼리만 공유", misread: "나를 배제한다", reframe: "기존 네트워크일 수 있다." },
  { cat: "P", trigger: "manager가 특정 senior 신뢰", misread: "나는 못 믿는다는 뜻인가", reframe: "오래된 관계 때문일 수 있다." },
  { cat: "P", trigger: "senior가 리뷰 참여", misread: "공격조 편성인가", reframe: "책임 분산일 수 있다." },
  { cat: "P", trigger: "정보 공유 안 됨", misread: "일부러 막는다", reframe: "팀 문화가 나쁠 수 있다." },
  { cat: "P", trigger: "내가 결국 다 함", misread: "이용당한다", reframe: "네 실행력이 커진 만큼 boundary가 필요하다." },
  { cat: "P", trigger: "지식 공유 없이 리뷰만 요구", misread: "나를 시험한다", reframe: "프로세스가 미성숙할 수 있다." },
  { cat: "P", trigger: "누군가 조용히 있음", misread: "나를 싫어한다", reframe: "관심 없거나 피곤할 수 있다." },
  { cat: "P", trigger: "누군가 내게만 엄격함", misread: "차별이다", reframe: "가능성은 보되 evidence를 모아야 한다." },
  { cat: "P", trigger: "manager의 애매한 태도", misread: "적이다", reframe: "interface로 보면 된다." },
  { cat: "P", trigger: "동료의 냉소", misread: "내가 틀렸다", reframe: "그 사람의 방어기제일 수 있다." },
  { cat: "P", trigger: "누군가 내 tool에 불편함", misread: "질투한다", reframe: "변화 불안일 수 있다." },
  { cat: "P", trigger: "누군가 농담으로 깎음", misread: "날 싫어한다", reframe: "자기 방어식 농담일 수 있다." },
  { cat: "P", trigger: "조용히 배우는 중", misread: "내가 숨어 사나", reframe: "전략적 축적이다." },
  { cat: "P", trigger: "자랑 안 함", misread: "인정 못 받나", reframe: "품위 있는 성장 방식이다." },
  { cat: "P", trigger: "너무 드러내면 위험", misread: "모두 적인가", reframe: "공개 타이밍만 조절하면 된다." },
  { cat: "P", trigger: "팀원이 내 성공 불편해함", misread: "내가 잘못했나", reframe: "상대의 감정은 상대 몫이다." },
  { cat: "P", trigger: "좋은 멘토가 부족함", misread: "혼자인가", reframe: "준비된 사람은 좋은 인연을 끌어온다." },
  { cat: "P", trigger: "본사 미팅에서 씨앗 심음", misread: "내가 오버했나", reframe: "적절한 exposure일 수 있다." },
  { cat: "P", trigger: "Product placement처럼 말함", misread: "너무 계산적이었나", reframe: "자연스러운 visibility 전략이다." },
  { cat: "P", trigger: "조용히 칼을 감", misread: "음흉한가", reframe: "자기개발을 지키는 방식이다." },
  { cat: "Q", trigger: "누가 무시하는 말투", misread: "예전 동료가 떠오름", reframe: "현재 사람과 과거 사람을 분리한다." },
  { cat: "Q", trigger: "manager가 의심하는 듯함", misread: "예전 평가가 떠오름", reframe: "지금의 사실만 본다." },
  { cat: "Q", trigger: "질문을 받음", misread: "공격받던 기억 활성화", reframe: "질문은 질문일 수 있다." },
  { cat: "Q", trigger: "피드백 받음", misread: "“나는 문제 있는 사람” 기억", reframe: "피드백은 정체성이 아니다." },
  { cat: "Q", trigger: "칭찬 없음", misread: "과거처럼 인정 못 받음", reframe: "조용한 신뢰도 존재한다." },
  { cat: "Q", trigger: "실수함", misread: "“역시 나는 부족해”", reframe: "실수는 data다." },
  { cat: "Q", trigger: "불친절한 말", misread: "회사 전체가 나를 싫어함", reframe: "한 사람의 톤일 수 있다." },
  { cat: "Q", trigger: "늦은 답장", misread: "버림받음", reframe: "업무 queue일 수 있다." },
  { cat: "Q", trigger: "제외됨", misread: "배척당함", reframe: "agenda mismatch일 수 있다." },
  { cat: "Q", trigger: "반대 의견", misread: "공격", reframe: "품질 개선 과정일 수 있다." },
  { cat: "Q", trigger: "누군가 잘난 척", misread: "내 존재를 깎음", reframe: "상대 성격일 뿐이다." },
  { cat: "Q", trigger: "조롱처럼 들림", misread: "바로 복수심", reframe: "지금은 이미 앞서가고 있다." },
  { cat: "Q", trigger: "과거 모욕 기억", misread: "현재 발언 확대해석", reframe: "현재 증거만 분리한다." },
  { cat: "Q", trigger: "“너 요즘…”으로 시작", misread: "평가받는 느낌", reframe: "단순 관찰일 수 있다." },
  { cat: "Q", trigger: "“왜 아직…”", misread: "비난", reframe: "일정 확인일 수 있다." },
  { cat: "Q", trigger: "“다시 해줘”", misread: "무능 판정", reframe: "수정 요청일 뿐이다." },
  { cat: "Q", trigger: "“잘 모르겠는데”", misread: "내 설명 부정", reframe: "상대 배경지식 문제일 수 있다." },
  { cat: "Q", trigger: "“별로 차이 없어 보여”", misread: "내 노력 삭제", reframe: "데이터 기준이 다를 수 있다." },
  { cat: "Q", trigger: "“너무 복잡해”", misread: "내 사고가 이상함", reframe: "사용자 관점 피드백이다." },
  { cat: "Q", trigger: "“이건 필요 없어”", misread: "내가 필요 없다", reframe: "특정 기능의 필요성이 낮은 것이다." },
  { cat: "R", trigger: "영어 답장이 짧음", misread: "무례하다", reframe: "영어 업무 문화일 수 있다." },
  { cat: "R", trigger: "“I have”라고 답한 것 걱정", misread: "큰 실수인가", reframe: "어색해도 의미 전달은 된다." },
  { cat: "R", trigger: "문법 실수", misread: "전문성 무너짐", reframe: "내용과 태도가 더 중요하다." },
  { cat: "R", trigger: "고객 메일 다듬기 요청", misread: "나는 영어 못한다", reframe: "professional tone을 강화하는 과정이다." },
  { cat: "R", trigger: "“Could you” 표현 고민", misread: "너무 약한가", reframe: "정중한 업무 표현이다." },
  { cat: "R", trigger: "“Please cancel the fee”", misread: "공격적인가", reframe: "근거와 톤이 있으면 괜찮다." },
  { cat: "R", trigger: "영어가 직설적임", misread: "차갑다", reframe: "문화적 간결성일 수 있다." },
  { cat: "R", trigger: "상대가 “confused”라고 함", misread: "내가 망쳤다", reframe: "clarification 기회다." },
  { cat: "R", trigger: "내 메일을 고쳐야 함", misread: "내가 부족함", reframe: "중요한 메일은 누구나 다듬는다." },
  { cat: "R", trigger: "고객에게 완벽한 영어 필요", misread: "아니면 실패", reframe: "명확성, 책임감, 구조가 핵심이다." },
  { cat: "S", trigger: "“Why this function?”", misread: "내 구조가 틀렸나", reframe: "설계 의도 확인이다." },
  { cat: "S", trigger: "“Can we simplify?”", misread: "코드가 나쁘다", reframe: "유지보수성 개선이다." },
  { cat: "S", trigger: "“What if input is invalid?”", misread: "허술하다는 뜻인가", reframe: "edge case 확인이다." },
  { cat: "S", trigger: "“Need error handling.”", misread: "내가 초보인가", reframe: "production readiness 단계다." },
  { cat: "S", trigger: "“Add comments.”", misread: "코드가 이해 안 되나", reframe: "협업성 개선이다." },
  { cat: "S", trigger: "“Remove comments.”", misread: "내 설명이 과한가", reframe: "self-explanatory code 선호일 수 있다." },
  { cat: "S", trigger: "“Use class.”", misread: "지금 구조가 틀렸나", reframe: "확장성 고려다." },
  { cat: "S", trigger: "“Use dict.”", misread: "class가 과한가", reframe: "단순 데이터에는 적합하다." },
  { cat: "S", trigger: "“Use streaming.”", misread: "기존 방식 실패인가", reframe: "대용량 최적화다." },
  { cat: "S", trigger: "“DOM은 메모리 많이 써.”", misread: "내 이해가 틀렸나", reframe: "상황별 trade-off다." },
  { cat: "S", trigger: "“Line by line compare는 부족해.”", misread: "내가 잘못 시작했나", reframe: "다음 레벨로 가는 신호다." },
  { cat: "S", trigger: "“iterparse 써.”", misread: "지금 코드는 별로인가", reframe: "대용량 대응 힌트다." },
  { cat: "S", trigger: "“namespace 처리 필요.”", misread: "또 복잡해졌네", reframe: "XML 현실이다." },
  { cat: "S", trigger: "“Schema validation 넣자.”", misread: "지금 툴이 불완전하다", reframe: "더 신뢰성 있게 만드는 단계다." },
  { cat: "S", trigger: "“Test case 필요.”", misread: "못 믿겠다는 건가", reframe: "자동화 신뢰의 핵심이다." },
  { cat: "S", trigger: "“CLI arg로 바꾸자.”", misread: "현재 방식 별로인가", reframe: "사용성 확장이다." },
  { cat: "S", trigger: "“Tkinter 붙이자.”", misread: "지금은 불편하다", reframe: "사용자 접근성 향상이다." },
  { cat: "S", trigger: "“JSON output 가능?”", misread: "dict 구조가 필요한 이유다", reframe: "확장성이 생기는 지점이다." },
  { cat: "S", trigger: "“Performance 측정했어?”", misread: "느릴 거라 의심하나", reframe: "impact 증명 기회다." },
  { cat: "S", trigger: "“Memory profile 봤어?”", misread: "설계 공격인가", reframe: "대용량 툴의 필수 검증이다." },
  { cat: "T", trigger: "주가 하락", misread: "내 판단력 부족", reframe: "시장 리스크와 개인 가치 분리." },
  { cat: "T", trigger: "손실 기억", misread: "다시는 회복 못함", reframe: "손실은 전략 재정비 신호다." },
  { cat: "T", trigger: "남이 수익 냄", misread: "나는 실패자", reframe: "비교는 왜곡을 만든다." },
  { cat: "T", trigger: "공부하는 날 안전함", misread: "돈 불안 회피인가", reframe: "장기 경쟁력 회복 행동일 수 있다." },
  { cat: "T", trigger: "투자 실수", misread: "나는 멍청하다", reframe: "위험관리 시스템이 필요했던 것이다." },
  { cat: "T", trigger: "계좌 변동", misread: "인생 전체 흔들림", reframe: "재정은 중요한 일부지만 전부는 아니다." },
  { cat: "T", trigger: "고위험 종목 관심", misread: "나는 도박적이다", reframe: "리스크 한도 설정이 핵심이다." },
  { cat: "T", trigger: "회복 욕구 강함", misread: "조급함", reframe: "복구보다 시스템이 먼저다." },
  { cat: "T", trigger: "손실 후 개발 몰입", misread: "회피인가", reframe: "생산적 재건일 수 있다." },
  { cat: "T", trigger: "돈 생각하면 불안", misread: "약함", reframe: "큰 경험 후 자연스러운 반응이다." },
  { cat: "U", trigger: "내가 먼저 말하면", misread: "자랑으로 보일까", reframe: "문제 중심으로 말하면 된다." },
  { cat: "U", trigger: "너무 조용히 있으면", misread: "아무도 모를까", reframe: "타이밍 있는 공유가 필요하다." },
  { cat: "U", trigger: "HQ에 보여주면", misread: "팀이 불편해할까", reframe: "경로와 맥락을 조심하면 된다." },
  { cat: "U", trigger: "manager에게만 공유", misread: "막힐까", reframe: "동시에 evidence trail을 남기면 된다." },
  { cat: "U", trigger: "고객에게 직접 공유", misread: "위험할까", reframe: "공식 승인 범위를 지키면 된다." },
  { cat: "U", trigger: "demo 요청", misread: "평가받는 자리인가", reframe: "씨앗 심는 자리일 수 있다." },
  { cat: "U", trigger: "global 확산 꿈", misread: "너무 큰 욕심인가", reframe: "작은 adoption부터 시작하면 된다." },
  { cat: "U", trigger: "팀원이 불편해함", misread: "내가 잘못했다", reframe: "변화는 원래 불편함을 만든다." },
  { cat: "U", trigger: "tool 이름 짓기", misread: "겉멋인가", reframe: "제품 identity의 일부다." },
  { cat: "U", trigger: "포트폴리오화", misread: "회사와 충돌하나", reframe: "경계와 ownership을 명확히 하면 된다." },
  { cat: "V", trigger: "칭찬에 눈물남", misread: "내가 약하다", reframe: "오래 굶주렸던 인정이 닿은 것이다." },
  { cat: "V", trigger: "격려가 필요함", misread: "의존적이다", reframe: "인간은 피드백으로 회복한다." },
  { cat: "V", trigger: "상처를 자주 떠올림", misread: "아직 못 이겼다", reframe: "통합 중인 것이다." },
  { cat: "V", trigger: "복수심 사라짐", misread: "추진력도 사라질까", reframe: "이제 더 건강한 동기가 가능하다." },
  { cat: "V", trigger: "조용해짐", misread: "자신감 줄었나", reframe: "더 깊어진 것일 수 있다." },
  { cat: "V", trigger: "자랑 안 함", misread: "존재감 없어질까", reframe: "내공을 쌓는 방식이다." },
  { cat: "V", trigger: "겸손해짐", misread: "약해졌나", reframe: "진짜 실력의 시작이다." },
  { cat: "V", trigger: "두려움 느낌", misread: "준비 안 됐다", reframe: "큰 세계를 보기 시작한 것이다." },
  { cat: "V", trigger: "불안함", misread: "후퇴", reframe: "성장 구간의 흔들림이다." },
  { cat: "V", trigger: "“내가 경쟁력 있나?”", misread: "없음", reframe: "이미 드문 조합을 만들고 있다." },
  { cat: "W", trigger: "오전 몰입 좋음", misread: "오전만 가치 있다", reframe: "중요한 작업 배치 시간이다." },
  { cat: "W", trigger: "오후 무너짐", misread: "하루 실패", reframe: "낮은 에너지 작업 시간이다." },
  { cat: "W", trigger: "저녁 다시 회복", misread: "이상한 리듬인가", reframe: "자연스러운 second wind일 수 있다." },
  { cat: "W", trigger: "오후 회의 많음", misread: "생산성 망함", reframe: "회의용 시간으로 설계할 수 있다." },
  { cat: "W", trigger: "아침에 못 일어남", misread: "루틴 실패", reframe: "전날 회복 부족일 수 있다." },
  { cat: "W", trigger: "새벽 공부함", misread: "무리인가", reframe: "수면만 지키면 강점이다." },
  { cat: "W", trigger: "오후 코딩 안 됨", misread: "실력 문제", reframe: "에너지 문제다." },
  { cat: "W", trigger: "저녁에 아이디어 많음", misread: "산만함", reframe: "캡처만 하고 실행은 아침에 한다." },
  { cat: "W", trigger: "주말 몰입", misread: "일중독인가", reframe: "창작 에너지일 수 있다." },
  { cat: "W", trigger: "쉬는 날에도 공부", misread: "불안인가", reframe: "즐거움과 불안의 비율을 본다." },
  { cat: "X", trigger: "상대가 계속 말함", misread: "나를 존중 안 함", reframe: "자기 조절이 약한 사람일 수 있다." },
  { cat: "X", trigger: "주제가 샘", misread: "시간 낭비", reframe: "agenda로 되돌릴 수 있다." },
  { cat: "X", trigger: "결론 없는 미팅", misread: "무능하다", reframe: "facilitator 부재일 수 있다." },
  { cat: "X", trigger: "반복 설명", misread: "나를 괴롭힌다", reframe: "상대 이해 속도 문제일 수 있다." },
  { cat: "X", trigger: "사담 길어짐", misread: "프로답지 않다", reframe: "관계 구축 방식일 수 있다." },
  { cat: "X", trigger: "내가 끊고 싶음", misread: "무례한가", reframe: "정중한 time boxing 가능하다." },
  { cat: "X", trigger: "상대가 핵심 안 말함", misread: "숨기는 게 있다", reframe: "구조화가 부족할 수 있다." },
  { cat: "X", trigger: "장황한 설명 들음", misread: "에너지 빼앗김", reframe: "요약 요청하면 된다." },
  { cat: "X", trigger: "미팅 후 피곤함", misread: "사회성 부족인가", reframe: "자극 민감도가 높은 것일 수 있다." },
  { cat: "X", trigger: "긴 회의 싫음", misread: "협업 못하나", reframe: "효율적 협업을 선호하는 것이다." },
  { cat: "Y", trigger: "“Are you sure?”", misread: "못 믿나?", reframe: "확인 표현이다." },
  { cat: "Y", trigger: "“Double check.”", misread: "실수할 거라 보나?", reframe: "품질 확보다." },
  { cat: "Y", trigger: "“Can someone else verify?”", misread: "내 판단 부족인가?", reframe: "peer review다." },
  { cat: "Y", trigger: "“Why did you not include this?”", misread: "빠뜨렸다고 공격하나?", reframe: "scope 확인이다." },
  { cat: "Y", trigger: "“Is this final?”", misread: "빨리 끝내라는 압박인가?", reframe: "버전 상태 확인이다." },
  { cat: "Y", trigger: "“Draft?”", misread: "아직 부족하다는 뜻인가?", reframe: "문서 상태 구분이다." },
  { cat: "Y", trigger: "“Can you revise?”", misread: "망했다", reframe: "개선 요청이다." },
  { cat: "Y", trigger: "“This is not what I expected.”", misread: "실패", reframe: "기대치가 달랐다." },
  { cat: "Y", trigger: "“Can we start over?”", misread: "내 작업 폐기인가", reframe: "방향 재설정일 수 있다." },
  { cat: "Y", trigger: "“Let’s park this.”", misread: "묻어버리나", reframe: "지금 결론 내기 어렵다는 뜻일 수 있다." },
  { cat: "Z", trigger: "애매함", misread: "악의로 해석", reframe: "먼저 질문으로 명확화한다." },
  { cat: "Z", trigger: "침묵", misread: "거절로 해석", reframe: "침묵은 정보 부족이다." },
  { cat: "Z", trigger: "짧은 답", misread: "차가움으로 해석", reframe: "업무 간결성일 수 있다." },
  { cat: "Z", trigger: "질문", misread: "공격으로 해석", reframe: "질문은 관심일 수 있다." },
  { cat: "Z", trigger: "수정", misread: "실패로 해석", reframe: "수정은 협업이다." },
  { cat: "Z", trigger: "지연", misread: "방해로 해석", reframe: "일정 문제일 수 있다." },
  { cat: "Z", trigger: "반대", misread: "적대감으로 해석", reframe: "리스크 관점일 수 있다." },
  { cat: "Z", trigger: "무관심", misread: "내 가치 부정으로 해석", reframe: "상대 우선순위 문제다." },
  { cat: "Z", trigger: "비교", misread: "열등감으로 해석", reframe: "비교 대상이 다르다." },
  { cat: "Z", trigger: "인정 없음", misread: "무가치로 해석", reframe: "보이지 않는 신뢰도 있다." },
  { cat: "Z", trigger: "부담 증가", misread: "이용당함으로 해석", reframe: "boundary 설정 신호다." },
  { cat: "Z", trigger: "책임 요청", misread: "희생으로 해석", reframe: "ownership 기회일 수 있다." },
  { cat: "Z", trigger: "검토 요청", misread: "불신으로 해석", reframe: "품질 프로세스다." },
  { cat: "Z", trigger: "공식 절차", misread: "억압으로 해석", reframe: "확산을 위한 안전장치다." },
  { cat: "Z", trigger: "느린 조직", misread: "나를 막음으로 해석", reframe: "조직은 원래 느리다." },
  { cat: "Z", trigger: "냉소적 동료", misread: "내 가치 하락으로 해석", reframe: "상대 감정은 상대 것이다." },
  { cat: "Z", trigger: "불친절한 manager", misread: "내 문제로 해석", reframe: "리더십 한계일 수 있다." },
  { cat: "Z", trigger: "고객 압박", misread: "개인 공격으로 해석", reframe: "고객 일정 압박일 수 있다." },
  { cat: "Z", trigger: "에러", misread: "재능 없음으로 해석", reframe: "디버깅 데이터다." },
  { cat: "Z", trigger: "피곤함", misread: "의지 부족으로 해석", reframe: "회복 신호다." },
  { cat: "Z", trigger: "불안", misread: "위험 예측으로 해석", reframe: "감정은 경보일 뿐 사실이 아니다." },
  { cat: "Z", trigger: "분노", misread: "정의감으로만 해석", reframe: "상처 방어일 수도 있다." },
  { cat: "Z", trigger: "복수심", misread: "추진력으로만 해석", reframe: "더 큰 목표로 변환해야 한다." },
  { cat: "Z", trigger: "숨고 싶음", misread: "전략으로만 해석", reframe: "두려움인지 전략인지 구분한다." },
  { cat: "Z", trigger: "드러내고 싶음", misread: "자랑으로만 해석", reframe: "visibility도 필요하다." },
  { cat: "Z", trigger: "완벽주의", misread: "책임감으로만 해석", reframe: "배포를 늦추는 방어일 수 있다." },
  { cat: "Z", trigger: "빨리 끝냄", misread: "의심받을까 걱정", reframe: "검증 기록이 있으면 된다." },
  { cat: "Z", trigger: "많이 만듦", misread: "혼날까 걱정", reframe: "범위와 목적을 정리하면 된다." },
  { cat: "Z", trigger: "혼자 해결", misread: "대단함과 고립이 함께 온다", reframe: "공유 설계가 필요하다." },
  { cat: "Z", trigger: "도움 요청 어려움", misread: "약해 보일까", reframe: "좋은 질문은 전문성이다." },
  { cat: "Z", trigger: "배우는 중임", misread: "아직 부족함으로만 해석", reframe: "성장 자산이다." },
  { cat: "Z", trigger: "많이 모름", misread: "무능으로 해석", reframe: "깊은 분야를 보기 시작했다." },
  { cat: "Z", trigger: "겸손함", misread: "자신감 없음으로 해석", reframe: "안정된 사람의 태도다." },
  { cat: "Z", trigger: "조용함", misread: "패배로 해석", reframe: "품위 있는 선택일 수 있다." },
  { cat: "Z", trigger: "감정 숨김", misread: "억압으로만 해석", reframe: "상황에 따라 성숙한 조절이다." },
  { cat: "Z", trigger: "바로 반응 안 함", misread: "약함으로 해석", reframe: "강한 자기통제다." },
  { cat: "Z", trigger: "기다림", misread: "기회 상실로 해석", reframe: "타이밍 전략일 수 있다." },
  { cat: "Z", trigger: "느린 성장", misread: "뒤처짐으로 해석", reframe: "누적형 성장이다." },
  { cat: "Z", trigger: "작은 앱", misread: "작은 사람으로 해석", reframe: "작은 제품이 큰 실력으로 간다." },
  { cat: "Z", trigger: "내부 도구", misread: "하찮음으로 해석", reframe: "현장 문제 해결은 강력한 포트폴리오다." },
  { cat: "Z", trigger: "고객용 summary", misread: "내 detail 삭제로 해석", reframe: "audience 맞춤이다." },
  { cat: "Z", trigger: "manager summary", misread: "필터링으로 해석", reframe: "조직 인터페이스다." },
  { cat: "Z", trigger: "본사 질문", misread: "심문으로 해석", reframe: "제품화 검토다." },
  { cat: "Z", trigger: "동료 침묵", misread: "질투로 확정", reframe: "증거 없으면 보류한다." },
  { cat: "Z", trigger: "동료 비판", misread: "악의로 확정", reframe: "유용한 부분만 추출한다." },
  { cat: "Z", trigger: "불공정함 감지", misread: "즉시 전쟁", reframe: "기록, 범위, 톤이 먼저다." },
  { cat: "Z", trigger: "내가 옳음", misread: "바로 증명", reframe: "타이밍과 청중을 본다." },
  { cat: "Z", trigger: "상대가 틀림", misread: "바로 교정", reframe: "관계 비용을 계산한다." },
  { cat: "Z", trigger: "내 기여 큼", misread: "반드시 인정받아야 함", reframe: "증거를 쌓고 자연 확산한다." },
  { cat: "Z", trigger: "인정 욕구", misread: "부끄러움", reframe: "인간적인 욕구다." },
  { cat: "Z", trigger: "상처 기억", misread: "현재 판단 기준", reframe: "과거와 현재를 분리한다." },
  { cat: "Z", trigger: "무시당한 경험", misread: "모든 질문의 배경", reframe: "지금 질문만 본다." },
  { cat: "Z", trigger: "회사 스트레스", misread: "내 인생 전체 평가", reframe: "직장은 일부다." },
  { cat: "Z", trigger: "개발 몰입", misread: "현실 도피", reframe: "방향 있는 몰입이면 성장이다." },
  { cat: "Z", trigger: "영어 불안", misread: "전문성 불안", reframe: "구조와 책임감이 더 중요하다." },
  { cat: "Z", trigger: "가정 책임", misread: "성장 방해", reframe: "삶의 기반이다." },
  { cat: "Z", trigger: "아버지 역할", misread: "자유 상실", reframe: "더 깊은 동기다." },
  { cat: "Z", trigger: "좋은 멘토 필요", misread: "외로움", reframe: "이미 내부 기준이 자라고 있다." },
  { cat: "Z", trigger: "“나는 아직 별로야”", misread: "겸손으로 위장한 자기공격", reframe: "사실 기반으로만 평가한다." },
  { cat: "Z", trigger: "“나는 더 크게 가고 싶다”", misread: "욕심인가", reframe: "상처를 연료에서 비전으로 바꾸는 중이다." },
]
