// 노아 전용 리프레임 라이브러리 v2 — 큐레이션 500개.
// noah-reframes-2.txt(trigger|오해|emotion|best_response) 기반, reframe는 v1에서 트리거 매칭 백필.
// 자동 생성(일회성). 파서가 입력과 매칭해 노아 본인의 해석+품위 있는 다음 행동을 surface.
export const REFRAMES = [
  { cat:"A", trigger:"“이번 주 WFH 며칠이야?”", misread:"나를 감시한다", emotion:"불안, 방어심", best:"일정만 짧게 공유하고 해명하지 않는다.", reframe:"단순 일정 확인일 수 있다." },
  { cat:"A", trigger:"“이거 오늘 안에 가능해?”", misread:"압박한다", emotion:"부담감, 긴장", best:"가능 범위와 리스크를 함께 말한다.", reframe:"우선순위 확인일 수 있다." },
  { cat:"A", trigger:"“왜 이렇게 했어?”", misread:"내 판단을 의심한다", emotion:"억울함, 방어심", best:"결정 배경을 사실 중심으로 설명한다.", reframe:"의사결정 배경을 묻는 것일 수 있다." },
  { cat:"A", trigger:"“다른 옵션은 봤어?”", misread:"내 방식이 틀렸다는 뜻이다", emotion:"불안, 자존심 상함", best:"검토한 옵션과 선택 이유를 정리한다.", reframe:"리스크 체크일 수 있다." },
  { cat:"A", trigger:"“슬라이드 제목이 애매한데?”", misread:"꼬투리 잡는다", emotion:"짜증, 수치심", best:"메시지 목적에 맞게 제목을 수정한다.", reframe:"메시지 명확화 요청일 수 있다." },
  { cat:"A", trigger:"“고객에게 어떻게 설명할 거야?”", misread:"내가 설명 못한다고 본다", emotion:"불안, 압박감", best:"고객용 한 문장 요약을 준비한다.", reframe:"커뮤니케이션 준비일 수 있다." },
  { cat:"A", trigger:"“잠깐 같이 보자.”", misread:"문제가 생겼다", emotion:"긴장, 경계심", best:"agenda를 확인하고 사실 자료를 준비한다.", reframe:"빠른 싱크업일 수 있다." },
  { cat:"A", trigger:"“이 부분은 좀 더 다듬자.”", misread:"결과물이 부족하다", emotion:"실망, 수치심", best:"수정 요청을 작업 항목으로 분리한다.", reframe:"완성도 향상 과정일 수 있다." },
  { cat:"A", trigger:"“너무 빨리 끝낸 거 아니야?”", misread:"내 결과를 의심한다", emotion:"억울함, 분노", best:"검증 방식과 완료 기준을 보여준다.", reframe:"범위와 검증 수준을 확인하는 것일 수 있다." },
  { cat:"A", trigger:"“누가 리뷰했어?”", misread:"나를 못 믿는다", emotion:"방어심, 불쾌감", best:"리뷰 상태와 필요한 추가 검토를 말한다.", reframe:"프로세스 확인일 수 있다." },
  { cat:"A", trigger:"“A랑도 같이 리뷰하자.”", misread:"나 혼자는 못 믿는다", emotion:"불안, 경계심", best:"리뷰 목적과 역할을 명확히 한다.", reframe:"이해관계자 alignment일 수 있다." },
  { cat:"A", trigger:"“고객에게 보내기 전 먼저 공유해줘.”", misread:"나를 통제한다", emotion:"답답함, 방어심", best:"초안 공유를 리스크 관리로 받아들인다.", reframe:null },
  { cat:"A", trigger:"“이건 좀 기다리자.”", misread:"내 기회를 막는다", emotion:"좌절, 조급함", best:"기다리는 이유와 다음 체크포인트를 묻는다.", reframe:"타이밍 조율일 수 있다." },
  { cat:"A", trigger:"“너무 많이 만들 필요 없어.”", misread:"내 성장을 막는다", emotion:"반발심, 서운함", best:"현재 범위와 backlog를 분리한다.", reframe:"범위 관리일 수 있다." },
  { cat:"A", trigger:"“지금은 이 일에 집중하자.”", misread:"내 아이디어를 무시한다", emotion:"답답함, 서운함", best:"현재 priority를 완료하고 아이디어는 기록한다.", reframe:"현재 우선순위가 다를 수 있다." },
  { cat:"A", trigger:"“그건 나중에 해도 돼.”", misread:"가치가 없다는 뜻이다", emotion:"실망, 무력감", best:"나중의 기준과 timing을 확인한다.", reframe:"타이밍 문제일 수 있다." },
  { cat:"A", trigger:"“간단히 요약해줘.”", misread:"내가 장황하다", emotion:"민망함, 방어심", best:"executive summary로 압축한다.", reframe:"의사결정용 압축을 원하는 것일 수 있다." },
  { cat:"A", trigger:"“디테일은 빼도 돼.”", misread:"내 노력이 지워진다", emotion:"허탈함, 서운함", best:"appendix나 backup slide로 보존한다.", reframe:"청중 수준에 맞추려는 것일 수 있다." },
  { cat:"A", trigger:"“너 혼자 다 하지 말고 공유해.”", misread:"내가 독단적이라는 뜻이다", emotion:"억울함, 방어심", best:"공유 채널과 ownership을 정리한다.", reframe:"지식 분산 요청일 수 있다." },
  { cat:"A", trigger:"“이건 팀 차원에서 해야 해.”", misread:"내 공을 가져간다", emotion:"경계심, 서운함", best:"내 기여 기록을 남기고 팀 확산 구조를 만든다.", reframe:"확산을 위해 조직화하는 것일 수 있다." },
  { cat:"A", trigger:"“아직 early stage야.”", misread:"내 수준이 낮다", emotion:"실망, 불안", best:"prototype 기준과 production 기준을 구분한다.", reframe:"배포 준비도에 대한 의견일 수 있다." },
  { cat:"A", trigger:"“고객 반응을 먼저 보자.”", misread:"내 판단을 안 믿는다", emotion:"불안, 답답함", best:"validation plan으로 전환한다.", reframe:"실제 validation을 원하는 것일 수 있다." },
  { cat:"A", trigger:"“왜 이게 필요한지 설명해줘.”", misread:"가치가 없다고 본다", emotion:"방어심, 긴장", best:"problem, impact, time saving으로 설명한다.", reframe:"business case를 묻는 것일 수 있다." },
  { cat:"A", trigger:"“기존 툴과 차이가 뭐야?”", misread:"내 작업이 중복이다", emotion:"불안, 서운함", best:"차별점 3개를 정리한다.", reframe:"차별점을 정리할 기회일 수 있다." },
  { cat:"A", trigger:"“공식 프로세스에 맞춰야 해.”", misread:"나를 막는다", emotion:"답답함, 반발심", best:"governance 요구사항을 체크리스트로 만든다.", reframe:"지속 가능성을 위한 조건일 수 있다." },
  { cat:"A", trigger:"“customer-facing은 조심하자.”", misread:"나를 못 믿는다", emotion:"방어심, 불안", best:"내부용/외부용 버전을 분리한다.", reframe:"외부 노출 리스크 관리일 수 있다." },
  { cat:"A", trigger:"“이메일 먼저 나한테 보여줘.”", misread:"검열당한다", emotion:"답답함, 불쾌감", best:"톤 리뷰로 보고 초안을 공유한다.", reframe:"톤 조율일 수 있다." },
  { cat:"A", trigger:"“이 내용은 너무 technical해.”", misread:"설명을 못했다", emotion:"민망함, 수치심", best:"청중 수준에 맞춰 technical depth를 낮춘다.", reframe:"청중 맞춤 요청일 수 있다." },
  { cat:"A", trigger:"“이건 너무 high-level이야.”", misread:"내용이 빈약하다", emotion:"불안, 초조함", best:"필요한 근거 데이터를 추가한다.", reframe:"필요한 detail level이 다를 수 있다." },
  { cat:"A", trigger:"“timeline 다시 정리해줘.”", misread:"내가 지연시킨다고 본다", emotion:"억울함, 부담감", best:"완료/진행/blocked 항목으로 나눈다.", reframe:"계획 가시화 요청일 수 있다." },
  { cat:"A", trigger:"“너 요즘 바빠 보여.”", misread:"성과가 안 보인다는 뜻이다", emotion:"불안, 경계심", best:"workload를 간단히 공유하고 우선순위를 묻는다.", reframe:"workload 체크일 수 있다." },
  { cat:"A", trigger:"“괜찮아?”", misread:"내가 흔들려 보인다", emotion:"민망함, 불안", best:"감사히 받고 필요한 지원만 말한다.", reframe:"단순 배려일 수 있다." },
  { cat:"A", trigger:"“요즘 뭐 하고 있어?”", misread:"감시한다", emotion:"방어심, 긴장", best:"주요 작업 3개만 status로 답한다.", reframe:"status update 요청일 수 있다." },
  { cat:"A", trigger:"“다음 단계가 뭐야?”", misread:"지금까지 부족했다", emotion:"압박감, 불안", best:"next action과 ETA를 제시한다.", reframe:"action item 확인일 수 있다." },
  { cat:"A", trigger:"“아직 공유하지 말자.”", misread:"숨기려 한다", emotion:"좌절, 의심", best:"공유 보류 이유와 재검토 시점을 묻는다.", reframe:"타이밍 조절일 수 있다." },
  { cat:"A", trigger:"“A가 이 부분 더 잘 알아.”", misread:"나를 배제한다", emotion:"서운함, 열등감", best:"A를 정보원으로 활용하고 내 역할을 유지한다.", reframe:"subject expert 연결일 수 있다." },
  { cat:"A", trigger:"“그건 네 영역이 아니야.”", misread:"성장 기회를 막는다", emotion:"반발심, 실망", best:"boundary를 인정하되 learning interest는 기록한다.", reframe:"ownership boundary일 수 있다." },
  { cat:"A", trigger:"“작은 버전으로 가자.”", misread:"큰 그림을 못 본다", emotion:"답답함, 조급함", best:"MVP와 future roadmap을 분리한다.", reframe:"adoption 전략일 수 있다." },
  { cat:"A", trigger:"“완벽하게 하려고 하지 마.”", misread:"대충 하라는 뜻이다", emotion:"불안, 반발심", best:"완료 기준을 명확히 정한다.", reframe:"과투입 방지일 수 있다." },
  { cat:"A", trigger:"“나중에 평가하자.”", misread:"인정을 미룬다", emotion:"서운함, 불안", best:"평가 기준과 evidence를 계속 축적한다.", reframe:"결과가 쌓인 뒤 판단하려는 것일 수 있다." },
  { cat:"A", trigger:"“회의에서 다시 얘기하자.”", misread:"지금 대답 피한다", emotion:"불안, 답답함", best:"회의 전 핵심 포인트를 메일로 정리한다.", reframe:null },
  { cat:"A", trigger:"“이건 좀 sensitive해.”", misread:"내가 선 넘었다", emotion:"불안, 수치심", best:"민감한 부분과 안전한 표현을 구분한다.", reframe:null },
  { cat:"A", trigger:"“scope 줄이자.”", misread:"내 아이디어가 과하다", emotion:"실망, 방어심", best:"core 기능과 optional 기능을 분리한다.", reframe:null },
  { cat:"A", trigger:"“너무 깊게 들어가지 마.”", misread:"내 분석이 쓸모없다", emotion:"허탈함, 서운함", best:"현재 청중에게 필요한 depth만 남긴다.", reframe:null },
  { cat:"A", trigger:"“일단 customer need부터 보자.”", misread:"내 툴을 의심한다", emotion:"불안, 답답함", best:"customer pain point와 연결한다.", reframe:null },
  { cat:"A", trigger:"“이건 내가 보고 결정할게.”", misread:"나를 배제한다", emotion:"무력감, 불쾌감", best:"결정에 필요한 자료를 정리해 넘긴다.", reframe:null },
  { cat:"A", trigger:"“아직 확정하지 마.”", misread:"내 판단을 못 믿는다", emotion:"불안, 방어심", best:"draft 상태로 표시하고 열린 이슈를 둔다.", reframe:null },
  { cat:"A", trigger:"“메일 톤이 강해.”", misread:"내가 감정적이라는 뜻이다", emotion:"민망함, 수치심", best:"facts-only 버전으로 낮춘다.", reframe:null },
  { cat:"A", trigger:"“좀 더 professional하게 쓰자.”", misread:"내가 미숙하다", emotion:"수치심, 방어심", best:"감정 표현을 줄이고 목적 중심으로 수정한다.", reframe:null },
  { cat:"A", trigger:"“내가 고객과 먼저 얘기할게.”", misread:"내 기회를 뺏는다", emotion:"서운함, 경계심", best:"내가 제공할 input과 follow-up 역할을 확보한다.", reframe:null },
  { cat:"B", trigger:"“그거 AI가 만든 거야?”", misread:"내 실력을 무시한다", emotion:"분노, 수치심", best:"농담으로 넘기지 말고 내가 구현한 핵심만 짧게 말한다.", reframe:"호기심 또는 농담일 수 있다." },
  { cat:"B", trigger:"“오, 이런 것도 했어?”", misread:"비꼰다", emotion:"경계심, 불쾌감", best:"의도를 단정하지 않고 기능을 설명한다.", reframe:"진짜 놀란 것일 수 있다." },
  { cat:"B", trigger:"“굳이 필요해?”", misread:"내 노력을 깎는다", emotion:"서운함, 분노", best:"해결한 문제와 시간 절감 효과를 말한다.", reframe:"사용성 질문일 수 있다." },
  { cat:"B", trigger:"“이미 비슷한 거 있지 않아?”", misread:"베낀 것으로 본다", emotion:"불안, 방어심", best:"기존 방식과 차이를 비교한다.", reframe:"중복 방지 질문일 수 있다." },
  { cat:"B", trigger:"“난 수동으로 할래.”", misread:"내 툴을 거부한다", emotion:"실망, 무력감", best:"강요하지 않고 필요한 때 쓰게 둔다.", reframe:"습관 문제일 수 있다." },
  { cat:"B", trigger:"“나중에 볼게.”", misread:"관심 없다", emotion:"서운함, 실망", best:"follow-up 시점만 정하고 밀어붙이지 않는다.", reframe:"실제로 시간이 없을 수 있다." },
  { cat:"B", trigger:"“이거 어떻게 쓰는 거야?”", misread:"UI가 별로다", emotion:"불안, 민망함", best:"사용법을 짧게 설명하고 개선 포인트로 기록한다.", reframe:"온보딩 기회일 수 있다." },
  { cat:"B", trigger:"“에러 나는데?”", misread:"툴이 실패했다", emotion:"긴장, 수치심", best:"재현 조건을 묻고 bug report로 처리한다.", reframe:"버그 리포트일 수 있다." },
  { cat:"B", trigger:"“내 방식이랑 달라.”", misread:"내가 틀렸다", emotion:"방어심, 불안", best:"workflow 차이를 확인하고 옵션화 가능성을 본다.", reframe:"워크플로우 차이일 수 있다." },
  { cat:"B", trigger:"“예전 방식이 편해.”", misread:"변화 거부다", emotion:"답답함, 실망", best:"기존 방식 존중 후 전환 이점을 보여준다.", reframe:"익숙함의 문제일 수 있다." },
  { cat:"B", trigger:"“공식 툴이야?”", misread:"비공식이라 문제 삼는다", emotion:"불안, 경계심", best:"사용 범위와 disclaimer를 명확히 한다.", reframe:"governance 확인일 수 있다." },
  { cat:"B", trigger:"“누가 승인했어?”", misread:"나를 공격한다", emotion:"방어심, 불쾌감", best:"승인 상태와 현재 단계만 답한다.", reframe:"사용 범위 확인일 수 있다." },
  { cat:"B", trigger:"“코드 공유 가능해?”", misread:"내 것을 가져가려 한다", emotion:"경계심, 불안", best:"공유 범위, 목적, ownership을 확인한다.", reframe:"협업 의도일 수 있다." },
  { cat:"B", trigger:"“문서 있어?”", misread:"준비 부족을 지적한다", emotion:"민망함, 불안", best:"quick guide를 만들고 링크한다.", reframe:"확산을 위한 요청일 수 있다." },
  { cat:"B", trigger:"“maintenance 누가 해?”", misread:"내가 감당 못한다고 본다", emotion:"압박감, 불안", best:"support model을 정의한다.", reframe:"장기 운영 질문일 수 있다." },
  { cat:"B", trigger:"“나도 비슷한 거 생각했는데.”", misread:"공을 가져간다", emotion:"경계심, 불쾌감", best:"공감하되 현재 구현 상태를 기록한다.", reframe:"단순 공감일 수 있다." },
  { cat:"B", trigger:"“고객한테 보여줘도 돼?”", misread:"나를 시험한다", emotion:"긴장, 불안", best:"외부 공유 가능 버전을 따로 준비한다.", reframe:null },
  { cat:"B", trigger:"“대단하네.”", misread:"비꼰다", emotion:"의심, 경계심", best:"칭찬일 가능성을 열어두고 감사한다.", reframe:"진짜 칭찬일 수 있다." },
  { cat:"B", trigger:"“너 요즘 코딩 많이 하네.”", misread:"본업 안 한다는 뜻이다", emotion:"불안, 방어심", best:"업무 효율화 목적이라고 짧게 말한다.", reframe:"관찰일 수 있다." },
  { cat:"B", trigger:"“언제 만들었어?”", misread:"근무시간 의심한다", emotion:"불안, 억울함", best:"개발 배경과 목적만 간단히 설명한다.", reframe:"제작 배경 궁금증일 수 있다." },
  { cat:"B", trigger:"“혼자 만든 거야?”", misread:"못 믿는다", emotion:"경계심, 자존심 상함", best:"사용한 기술과 구현 범위를 설명한다.", reframe:"놀람일 수 있다." },
  { cat:"B", trigger:"“꽤 복잡한데?”", misread:"문제가 많다는 뜻이다", emotion:"불안, 방어심", best:"핵심 흐름을 단순화해서 설명한다.", reframe:null },
  { cat:"B", trigger:"“천천히 설명해줘.”", misread:"내가 설명을 못했다", emotion:"민망함, 초조함", best:"한 단계씩 설명한다.", reframe:"상대가 따라오는 속도 문제일 수 있다." },
  { cat:"B", trigger:"“잘 모르겠어.”", misread:"관심 없다", emotion:"서운함, 답답함", best:"상대 배경지식에 맞춰 다시 말한다.", reframe:"도메인 차이일 수 있다." },
  { cat:"B", trigger:"“나한테는 필요 없을 듯.”", misread:"내 가치가 부정됐다", emotion:"실망, 무력감", best:"사용 대상이 다르다고 정리한다.", reframe:"사용자군이 다른 것일 수 있다." },
  { cat:"B", trigger:"“기능이 너무 많아.”", misread:"과하다는 비판이다", emotion:"불안, 방어심", best:"기본 모드와 고급 모드를 분리한다.", reframe:"UX 단순화 힌트일 수 있다." },
  { cat:"B", trigger:"“나중에 쓰면 좋겠다.”", misread:"지금은 별로다", emotion:"실망, 서운함", best:"지금 필요한 use case를 더 찾는다.", reframe:"타이밍 문제일 수 있다." },
  { cat:"B", trigger:"“고객 요구사항이야?”", misread:"개인 취미로 본다", emotion:"불안, 수치심", best:"실제 pain point와 연결한다.", reframe:"business need 확인일 수 있다." },
  { cat:"B", trigger:"“재밌네.”", misread:"가볍게 본다", emotion:"서운함, 불쾌감", best:"장난감처럼 방어하지 말고 impact를 말한다.", reframe:"긍정적 관심일 수 있다." },
  { cat:"B", trigger:"“demo 해봐.”", misread:"평가받는 자리다", emotion:"긴장, 불안", best:"demo script를 준비한다.", reframe:"기회일 수 있다." },
  { cat:"B", trigger:"“내가 봐줄게.”", misread:"내가 부족하다고 본다", emotion:"방어심, 자존심 상함", best:"도움으로 받아들이고 review scope를 정한다.", reframe:null },
  { cat:"B", trigger:"“내가 알던 거랑 다른데?”", misread:"내가 틀렸다", emotion:"긴장, 방어심", best:"기준 정보와 version을 확인한다.", reframe:"정보 차이일 수 있다." },
  { cat:"B", trigger:"“source가 뭐야?”", misread:"못 믿는다", emotion:"불안, 방어심", best:"근거 파일이나 데이터 위치를 제시한다.", reframe:"검증 습관일 수 있다." },
  { cat:"B", trigger:"“고객에게 말하면 위험하지 않아?”", misread:"막으려 한다", emotion:"답답함, 경계심", best:"risk와 safe wording을 분리한다.", reframe:"리스크 인식일 수 있다." },
  { cat:"B", trigger:"“팀 미팅에서 말하자.”", misread:"지금 피한다", emotion:"서운함, 불안", best:"팀 미팅용 3분 요약을 준비한다.", reframe:"더 큰 청중을 만들려는 것일 수 있다." },
  { cat:"B", trigger:"“manager랑 얘기했어?”", misread:"통제하려 한다", emotion:"불쾌감, 경계심", best:"alignment 상태를 사실대로 말한다.", reframe:"escalation path 확인일 수 있다." },
  { cat:"B", trigger:"“네가 계속 support해야 해?”", misread:"부담을 떠넘긴다", emotion:"압박감, 불안", best:"support boundary를 정한다.", reframe:"운영 모델 질문일 수 있다." },
  { cat:"B", trigger:"“버전 관리 돼?”", misread:"불신한다", emotion:"방어심, 긴장", best:"versioning 계획을 제시한다.", reframe:"툴 성숙도 질문일 수 있다." },
  { cat:"B", trigger:"“UI가 낯설어.”", misread:"디자인이 별로다", emotion:"민망함, 실망", best:"사용성 피드백으로 저장한다.", reframe:"개선 포인트일 수 있다." },
  { cat:"B", trigger:"“좋은데 헷갈려.”", misread:"실패했다", emotion:"불안, 실망", best:"onboarding flow를 개선한다.", reframe:null },
  { cat:"B", trigger:"“이거 누구한테 보여줬어?”", misread:"문제 삼으려 한다", emotion:"불안, 경계심", best:"공유 범위와 목적을 명확히 한다.", reframe:null },
  { cat:"B", trigger:"“너무 개인화돼 있어.”", misread:"공식화 불가다", emotion:"실망, 불안", best:"general version과 personal version을 나눈다.", reframe:null },
  { cat:"B", trigger:"“이건 우리 팀 방식이 아니야.”", misread:"배척한다", emotion:"답답함, 서운함", best:"팀 프로세스에 맞는 adapter를 생각한다.", reframe:null },
  { cat:"B", trigger:"“기존 파일이랑 호환돼?”", misread:"못 믿는다", emotion:"긴장, 방어심", best:"테스트 케이스를 보여준다.", reframe:null },
  { cat:"B", trigger:"“실제로 누가 쓸까?”", misread:"쓸모없다고 본다", emotion:"서운함, 분노", best:"target user와 scenario를 제시한다.", reframe:null },
  { cat:"B", trigger:"“좋긴 한데…”", misread:"곧 비판할 것이다", emotion:"긴장, 경계심", best:"뒤의 피드백을 끝까지 듣는다.", reframe:null },
  { cat:"B", trigger:"“너무 앞서간 거 아니야?”", misread:"오버한다고 본다", emotion:"수치심, 방어심", best:"현재 문제와 연결해 설명한다.", reframe:null },
  { cat:"B", trigger:"“그건 나중에 자동화해도 돼.”", misread:"중요하지 않다", emotion:"답답함, 실망", best:"자동화 ROI를 숫자로 정리한다.", reframe:"타이밍 문제일 수 있다." },
  { cat:"B", trigger:"“왜 이렇게 진지해?”", misread:"나를 우습게 본다", emotion:"수치심, 분노", best:"감정 반응 대신 목적을 짧게 말한다.", reframe:"의사결정 배경을 묻는 것일 수 있다." },
  { cat:"B", trigger:"“그냥 참고만 할게.”", misread:"무시한다", emotion:"서운함, 무력감", best:"강요하지 않고 사용 사례를 남긴다.", reframe:null },
  { cat:"C", trigger:"“Can you provide more details?”", misread:"설명이 부족하다", emotion:"불안, 긴장", best:"detail 자료를 구조화해 제공한다.", reframe:"추가 정보 요청이다." },
  { cat:"C", trigger:"“What is the evidence?”", misread:"나를 의심한다", emotion:"방어심, 불쾌감", best:"데이터, 로그, 비교 결과를 제시한다.", reframe:"기술 판단의 근거 요청이다." },
  { cat:"C", trigger:"“How did you validate this?”", misread:"대충 했다고 본다", emotion:"억울함, 긴장", best:"validation method를 단계별로 설명한다.", reframe:"검증 절차 확인이다." },
  { cat:"C", trigger:"“Is this reproducible?”", misread:"결과를 못 믿는다", emotion:"불안, 방어심", best:"재현 조건과 반복 테스트를 정리한다.", reframe:"제품화 가능성 확인이다." },
  { cat:"C", trigger:"“What is the scope?”", misread:"제한하려 한다", emotion:"답답함, 불안", best:"적용 범위와 제외 범위를 명확히 한다.", reframe:"적용 범위 정리다." },
  { cat:"C", trigger:"“What is the limitation?”", misread:"약점을 캐낸다", emotion:"경계심, 방어심", best:"limitation을 먼저 투명하게 제시한다.", reframe:"리스크 관리다." },
  { cat:"C", trigger:"“Compare with current method.”", misread:"새 툴을 부정한다", emotion:"긴장, 불안", best:"current vs new table을 만든다.", reframe:"impact 정량화 기회다." },
  { cat:"C", trigger:"“Who are the users?”", misread:"관심이 없다", emotion:"서운함, 불안", best:"user persona와 use case를 정의한다.", reframe:"adoption 대상 확인이다." },
  { cat:"C", trigger:"“What problem are you solving?”", misread:"가치가 없다는 뜻이다", emotion:"방어심, 수치심", best:"problem statement를 한 문장으로 말한다.", reframe:"problem statement 요구다." },
  { cat:"C", trigger:"“Is this scalable?”", misread:"지금 것은 작다", emotion:"불안, 열등감", best:"현재 버전과 확장 계획을 분리한다.", reframe:"확장성 질문이다." },
  { cat:"C", trigger:"“Send a concise summary.”", misread:"디테일이 쓸모없다", emotion:"서운함, 허탈함", best:"executive summary와 backup detail을 분리한다.", reframe:"decision maker용 요약이다." },
  { cat:"C", trigger:"“Align internally first.”", misread:"막으려 한다", emotion:"답답함, 의심", best:"내부 alignment를 다음 단계로 받아들인다.", reframe:"메시지 일관성 확보일 수 있다." },
  { cat:"C", trigger:"“Check compliance.”", misread:"내가 규정 위반했다", emotion:"불안, 수치심", best:"compliance checklist를 작성한다.", reframe:"공식화 전 절차다." },
  { cat:"C", trigger:"“This may overlap.”", misread:"작업이 불필요하다", emotion:"실망, 불안", best:"overlap과 unique value를 구분한다.", reframe:null },
  { cat:"C", trigger:"“Who owns this?”", misread:"공을 뺏는다", emotion:"경계심, 불안", best:"ownership과 contribution을 문서화한다.", reframe:"책임 구조 확인이다." },
  { cat:"C", trigger:"“Can this be maintained?”", misread:"내가 감당 못한다", emotion:"압박감, 방어심", best:"maintenance model을 제안한다.", reframe:"장기 운영성 질문이다." },
  { cat:"C", trigger:"“Do you have documentation?”", misread:"준비 부족이다", emotion:"민망함, 긴장", best:"quick start guide를 만든다.", reframe:"확산을 위한 필수 자료다." },
  { cat:"C", trigger:"“Share the architecture.”", misread:"코드를 가져가려 한다", emotion:"경계심, 불안", best:"high-level architecture부터 공유한다.", reframe:"이해와 검토 목적일 수 있다." },
  { cat:"C", trigger:"“What are dependencies?”", misread:"약점을 찾는다", emotion:"불안, 방어심", best:"dependency list와 risk mitigation을 제시한다.", reframe:"운영 리스크 확인이다." },
  { cat:"C", trigger:"“What is the failure mode?”", misread:"위험한 툴로 본다", emotion:"긴장, 방어심", best:"failure case와 fallback을 정리한다.", reframe:"안전 설계 질문이다." },
  { cat:"C", trigger:"“This is interesting.”", misread:"애매하게 거절한다", emotion:"불안, 답답함", best:"다음 action을 묻는다.", reframe:"초기 긍정 신호일 수 있다." },
  { cat:"C", trigger:"“Let us think about it.”", misread:"묻어둔다", emotion:"실망, 의심", best:"follow-up date를 제안한다.", reframe:"검토 시간이 필요한 것일 수 있다." },
  { cat:"C", trigger:"“Not now.”", misread:"가치가 없다", emotion:"좌절, 서운함", best:"timing reason과 revisit point를 확인한다.", reframe:"우선순위 문제일 수 있다." },
  { cat:"C", trigger:"“Revisit later.”", misread:"사실상 거절이다", emotion:"실망, 무력감", best:"backlog로 남기고 evidence를 더 모은다.", reframe:"타이밍 조정일 수 있다." },
  { cat:"C", trigger:"“Need customer input.”", misread:"내 판단을 못 믿는다", emotion:"불안, 방어심", best:"customer validation plan을 만든다.", reframe:"외부 validation 필요다." },
  { cat:"C", trigger:"“Not standard yet.”", misread:"하지 말라는 뜻이다", emotion:"답답함, 불안", best:"pilot/prototype label을 붙인다.", reframe:"표준화 전 단계라는 뜻이다." },
  { cat:"C", trigger:"“Make it simpler.”", misread:"설계가 별로다", emotion:"민망함, 방어심", best:"핵심 기능만 남긴 simplified flow를 만든다.", reframe:"사용자 확산을 위한 요청이다." },
  { cat:"C", trigger:"“Minimum viable version?”", misread:"큰 그림을 무시한다", emotion:"답답함, 조급함", best:"MVP와 roadmap을 구분한다.", reframe:"adoption entry point를 찾는 것이다." },
  { cat:"C", trigger:"“Separate personal and official process.”", misread:"나를 의심한다", emotion:"불안, 수치심", best:"개인 학습/업무 적용 경계를 명확히 한다.", reframe:"governance 구분이다." },
  { cat:"C", trigger:"“Avoid custom scripts.”", misread:"코딩을 막는다", emotion:"반발심, 좌절", best:"risk를 인정하고 approved path를 찾는다.", reframe:"유지보수 리스크 관점이다." },
  { cat:"C", trigger:"“Can you quantify impact?”", misread:"말만 한다고 본다", emotion:"긴장, 불안", best:"시간 절감, error reduction 지표를 산출한다.", reframe:null },
  { cat:"C", trigger:"“What is the business case?”", misread:"흥미 없다는 뜻이다", emotion:"서운함, 불안", best:"cost/time/risk 관점으로 설명한다.", reframe:"적용 범위 정리다." },
  { cat:"C", trigger:"“Do you have user feedback?”", misread:"내 말은 부족하다", emotion:"불안, 방어심", best:"beta feedback을 정리한다.", reframe:null },
  { cat:"C", trigger:"“Can this be integrated?”", misread:"standalone은 의미 없다", emotion:"실망, 불안", best:"integration 가능성과 제약을 적는다.", reframe:"장기 운영성 질문이다." },
  { cat:"C", trigger:"“Who supports rollout?”", misread:"확산을 막는다", emotion:"압박감, 불안", best:"rollout owner와 support plan을 제안한다.", reframe:null },
  { cat:"C", trigger:"“Security review needed.”", misread:"위험한 일을 했다", emotion:"불안, 긴장", best:"security review를 제품화 단계로 받아들인다.", reframe:"그냥 동의일 수 있다." },
  { cat:"C", trigger:"“Data privacy?”", misread:"내가 조심성 없다", emotion:"수치심, 불안", best:"민감 데이터 처리 원칙을 명시한다.", reframe:null },
  { cat:"C", trigger:"“Can you anonymize examples?”", misread:"내 사례가 문제다", emotion:"불안, 경계심", best:"customer/company 정보를 제거한다.", reframe:null },
  { cat:"C", trigger:"“Need approval chain.”", misread:"관료주의로 막는다", emotion:"답답함, 짜증", best:"approval path를 체크리스트로 만든다.", reframe:"맥락 없이는 판단 불가다." },
  { cat:"C", trigger:"“This is outside current roadmap.”", misread:"버려진다", emotion:"실망, 무력감", best:"roadmap fit을 찾거나 side pilot으로 유지한다.", reframe:"고객 일정상 중요하다는 의미다." },
  { cat:"C", trigger:"“We need to prioritize.”", misread:"내 일은 낮은 priority다", emotion:"서운함, 좌절", best:"priority 기준을 묻고 맞춘다.", reframe:null },
  { cat:"C", trigger:"“Can you provide a demo recording?”", misread:"live로는 못 믿는다", emotion:"불안, 방어심", best:"짧은 demo video를 만든다.", reframe:"추가 정보 요청이다." },
  { cat:"C", trigger:"“What is the user journey?”", misread:"UI가 미흡하다", emotion:"민망함, 불안", best:"user flow diagram을 만든다.", reframe:"결정 전 risk assessment다." },
  { cat:"C", trigger:"“Can you benchmark?”", misread:"성능 의심이다", emotion:"긴장, 방어심", best:"before/after benchmark를 만든다.", reframe:null },
  { cat:"C", trigger:"“What if it fails?”", misread:"실패를 기대한다", emotion:"불안, 경계심", best:"fallback과 manual recovery를 설명한다.", reframe:null },
  { cat:"C", trigger:"“Can we standardize naming?”", misread:"내 naming이 별로다", emotion:"수치심, 방어심", best:"naming convention을 맞춘다.", reframe:"방향 재설정일 수 있다." },
  { cat:"C", trigger:"“Can you create a one-pager?”", misread:"내 설명이 길다", emotion:"민망함, 불안", best:"one-page value summary를 만든다.", reframe:null },
  { cat:"C", trigger:"“Need stakeholder map.”", misread:"혼자서는 안 된다", emotion:"압박감, 불안", best:"관련자와 역할을 정리한다.", reframe:null },
  { cat:"C", trigger:"“We need to avoid confusion.”", misread:"내가 혼란을 만든다", emotion:"수치심, 방어심", best:"communication plan을 만든다.", reframe:"상대가 맥락을 놓쳤을 수 있다." },
  { cat:"C", trigger:"“Let’s keep this internal for now.”", misread:"숨긴다", emotion:"의심, 좌절", best:"internal pilot로 정의하고 exit criteria를 둔다.", reframe:"버전 상태 확인이다." },
  { cat:"D", trigger:"“When can we get the result?”", misread:"나를 압박한다", emotion:"부담감, 긴장", best:"현실적 ETA와 dependency를 말한다.", reframe:"일정 확인이다." },
  { cat:"D", trigger:"“Why is this delayed?”", misread:"내 책임으로 몰아간다", emotion:"억울함, 방어심", best:"원인, 영향, 다음 조치를 분리한다.", reframe:"원인 파악 요청이다." },
  { cat:"D", trigger:"“Any improvement?”", misread:"내 분석을 의심한다", emotion:"긴장, 불안", best:"현재 관찰 결과와 추가 확인 계획을 말한다.", reframe:"결과 판단 기준을 묻는 것이다." },
  { cat:"D", trigger:"“Can you show the data?”", misread:"못 믿는다", emotion:"방어심, 불쾌감", best:"관련 plot/table을 준비한다.", reframe:"객관적 근거 요청이다." },
  { cat:"D", trigger:"“Does not look improved.”", misread:"내 노력이 부정됐다", emotion:"실망, 억울함", best:"동의/불확실성/추가 분석으로 답한다.", reframe:"고객 시야에서는 아직 부족할 수 있다." },
  { cat:"D", trigger:"“Need more evidence.”", misread:"나를 공격한다", emotion:"긴장, 방어심", best:"필요한 evidence 목록을 정의한다.", reframe:"의사결정에 필요한 자료가 더 필요한 것이다." },
  { cat:"D", trigger:"“Can ASML confirm?”", misread:"나 개인을 못 믿는다", emotion:"서운함, 불안", best:"공식 confirmation 경로를 안내한다.", reframe:"공식 답변이 필요한 상황이다." },
  { cat:"D", trigger:"“Who is responsible?”", misread:"나를 몰아간다", emotion:"경계심, 불안", best:"ownership을 사실 기준으로 정리한다.", reframe:"ownership clarification이다." },
  { cat:"D", trigger:"“Can we escalate?”", misread:"내가 실패했다", emotion:"수치심, 압박감", best:"escalation을 빠른 해결 경로로 받아들인다.", reframe:"빠른 해결을 위한 경로다." },
  { cat:"D", trigger:"“This is urgent.”", misread:"몰아붙인다", emotion:"부담감, 긴장", best:"urgent 기준과 우선순위를 확인한다.", reframe:"고객 일정상 중요하다는 의미다." },
  { cat:"D", trigger:"“We expected better.”", misread:"내가 실망시켰다", emotion:"수치심, 좌절", best:"기대치와 현재 결과 차이를 인정하고 다음 액션을 제시한다.", reframe:"기대치 조정이 필요하다." },
  { cat:"D", trigger:"“Explain simply.”", misread:"내가 복잡하게 말했다", emotion:"민망함, 불안", best:"비기술적 요약으로 다시 설명한다.", reframe:null },
  { cat:"D", trigger:"“We already tried that.”", misread:"내 제안을 무시한다", emotion:"서운함, 당황", best:"과거 시도 결과와 차이를 묻는다.", reframe:"과거 시도 정보 제공이다." },
  { cat:"D", trigger:"“That will not work.”", misread:"나를 깎아내린다", emotion:"분노, 방어심", best:"반박 전에 이유를 묻는다.", reframe:"고객 경험 기반 우려다." },
  { cat:"D", trigger:"“Propose next steps.”", misread:"준비 안 됐다고 본다", emotion:"긴장, 압박감", best:"2~3개 action plan을 제시한다.", reframe:"action plan 요청이다." },
  { cat:"D", trigger:"“We need a meeting.”", misread:"문제 커졌다", emotion:"불안, 긴장", best:"agenda와 참석자를 확인한다.", reframe:"alignment가 필요한 상황일 수 있다." },
  { cat:"D", trigger:"“Send a written summary.”", misread:"말로는 못 믿는다", emotion:"방어심, 서운함", best:"written record로 활용한다.", reframe:"기록용 요청이다." },
  { cat:"D", trigger:"“This is not clear.”", misread:"설명 실패다", emotion:"민망함, 불안", best:"핵심 메시지를 다시 구조화한다.", reframe:"메시지 구조 개선 요청이다." },
  { cat:"D", trigger:"“Include timeline.”", misread:"지연 의심이다", emotion:"부담감, 방어심", best:"timeline과 blocker를 분리한다.", reframe:"planning clarity 요구다." },
  { cat:"D", trigger:"“What is the risk?”", misread:"위험한 제안이다", emotion:"긴장, 불안", best:"risk와 mitigation을 함께 제시한다.", reframe:"결정 전 risk assessment다." },
  { cat:"D", trigger:"“Can you guarantee?”", misread:"나를 몰아간다", emotion:"압박감, 불안", best:"보장 대신 confidence level과 조건을 말한다.", reframe:null },
  { cat:"D", trigger:"“Why didn’t we know earlier?”", misread:"숨겼다고 본다", emotion:"억울함, 긴장", best:"발견 시점과 communication history를 설명한다.", reframe:"우선순위 문제일 수 있다." },
  { cat:"D", trigger:"“This is unacceptable.”", misread:"나를 공격한다", emotion:"분노, 수치심", best:"감정 반응을 늦추고 사실과 조치를 답한다.", reframe:null },
  { cat:"D", trigger:"“We need root cause.”", misread:"네 분석이 부족하다", emotion:"부담감, 불안", best:"현재 known/unknown을 구분한다.", reframe:null },
  { cat:"D", trigger:"“Can you join today?”", misread:"내 일정은 무시된다", emotion:"답답함, 부담감", best:"가능 시간과 준비 가능 범위를 말한다.", reframe:null },
  { cat:"D", trigger:"“Need answer ASAP.”", misread:"압박한다", emotion:"긴장, 조급함", best:"빠른 preliminary answer와 full answer ETA를 나눈다.", reframe:null },
  { cat:"D", trigger:"“This is blocking us.”", misread:"내 탓이다", emotion:"죄책감, 부담감", best:"blocker impact를 인정하고 next step을 제시한다.", reframe:null },
  { cat:"D", trigger:"“Can you check again?”", misread:"내 확인을 못 믿는다", emotion:"방어심, 짜증", best:"재확인 기준을 정하고 결과를 공유한다.", reframe:"품질 확보다." },
  { cat:"D", trigger:"“We disagree.”", misread:"내가 틀렸다", emotion:"불안, 방어심", best:"disagreement point를 구체화한다.", reframe:null },
  { cat:"D", trigger:"“Need ASML position.”", misread:"내 답은 의미 없다", emotion:"서운함, 무력감", best:"개인 의견과 공식 입장을 구분한다.", reframe:null },
  { cat:"D", trigger:"“Customer wants by Friday.”", misread:"무리하게 압박한다", emotion:"부담감, 짜증", best:"가능한 범위와 risk를 명시한다.", reframe:null },
  { cat:"D", trigger:"“Can you stay on this?”", misread:"나만 붙잡힌다", emotion:"피로감, 답답함", best:"support window와 handoff 조건을 정한다.", reframe:null },
  { cat:"D", trigger:"“We don’t see value.”", misread:"내가 헛일했다", emotion:"좌절, 서운함", best:"value metric을 다시 맞춘다.", reframe:null },
  { cat:"D", trigger:"“Need comparison with previous run.”", misread:"내 현재 분석 부족", emotion:"긴장, 불안", best:"이전 run 대비 표를 만든다.", reframe:null },
  { cat:"D", trigger:"“What changed?”", misread:"내가 설명 안 했다", emotion:"불안, 방어심", best:"change log를 정리한다.", reframe:null },
  { cat:"D", trigger:"“Can you reproduce at our site?”", misread:"내 결과는 site-specific이다", emotion:"긴장, 불안", best:"재현 조건과 site difference를 설명한다.", reframe:"그냥 동의일 수 있다." },
  { cat:"D", trigger:"“This is not priority for us.”", misread:"내 일이 중요하지 않다", emotion:"실망, 무력감", best:"고객 priority에 맞는 angle을 찾는다.", reframe:"메시지 구조 개선 요청이다." },
  { cat:"D", trigger:"“We need management visibility.”", misread:"일이 커졌다", emotion:"불안, 압박감", best:"management용 concise summary를 만든다.", reframe:null },
  { cat:"D", trigger:"“Why no update?”", misread:"내가 방치했다", emotion:"죄책감, 방어심", best:"update cadence를 정한다.", reframe:"상태 확인일 수 있다." },
  { cat:"D", trigger:"“Please explain deviation.”", misread:"내 결과가 이상하다", emotion:"긴장, 불안", best:"deviation 원인 후보를 정리한다.", reframe:"의견 요청일 수 있다." },
  { cat:"D", trigger:"“This contradicts previous data.”", misread:"내가 틀렸다", emotion:"당황, 방어심", best:"dataset/version 차이를 확인한다.", reframe:"단순 데이터에는 적합하다." },
  { cat:"D", trigger:"“Can you confirm by email?”", misread:"못 믿는다", emotion:"방어심, 불쾌감", best:"기록을 남기는 절차로 받아들인다.", reframe:"공식 답변이 필요한 상황이다." },
  { cat:"D", trigger:"“We need action, not analysis.”", misread:"내 분석은 쓸모없다", emotion:"서운함, 압박감", best:"action item과 분석 근거를 분리한다.", reframe:"기록했다는 뜻이다." },
  { cat:"D", trigger:"“This is taking too long.”", misread:"내가 느리다", emotion:"수치심, 부담감", best:"진행 상황과 병목을 투명하게 말한다.", reframe:"초기 긍정 신호일 수 있다." },
  { cat:"D", trigger:"“Can we have daily updates?”", misread:"감시당한다", emotion:"답답함, 부담감", best:"짧은 daily template을 제안한다.", reframe:"상태 확인일 수 있다." },
  { cat:"D", trigger:"“Why ASML didn’t catch this?”", misread:"회사를 공격한다", emotion:"방어심, 긴장", best:"책임 논쟁보다 containment로 전환한다.", reframe:null },
  { cat:"D", trigger:"“What is your recommendation?”", misread:"틀리면 책임진다", emotion:"불안, 압박감", best:"recommendation과 assumptions를 함께 쓴다.", reframe:"그냥 동의일 수 있다." },
  { cat:"D", trigger:"“Can you be more specific?”", misread:"내가 애매하다", emotion:"민망함, 불안", best:"숫자, 조건, 예외를 추가한다.", reframe:"파일을 못 찾았을 수 있다." },
  { cat:"D", trigger:"“We need confidence level.”", misread:"못 믿는다", emotion:"긴장, 방어심", best:"high/medium/low confidence로 답한다.", reframe:"의사결정에 필요한 자료가 더 필요한 것이다." },
  { cat:"D", trigger:"“Please close this quickly.”", misread:"빨리 끝내라고 몰아붙인다", emotion:"부담감, 짜증", best:"closure criteria를 합의한다.", reframe:"의견 요청일 수 있다." },
  { cat:"E", trigger:"“?”", misread:"화났다", emotion:"불안, 긴장", best:"맥락을 묻거나 간단히 확인한다.", reframe:null },
  { cat:"E", trigger:"“Please advise.”", misread:"책임 떠넘긴다", emotion:"부담감, 짜증", best:"선택지와 추천안을 제시한다.", reframe:"의견 요청일 수 있다." },
  { cat:"E", trigger:"“Any update?”", misread:"독촉한다", emotion:"압박감, 방어심", best:"status와 next ETA를 짧게 답한다.", reframe:"상태 확인일 수 있다." },
  { cat:"E", trigger:"“Following up.”", misread:"압박한다", emotion:"긴장, 짜증", best:"이전 내용 확인 후 현재 상태를 답한다.", reframe:"놓치지 않기 위한 리마인더다." },
  { cat:"E", trigger:"“Let me know.”", misread:"무심하다", emotion:"서운함, 불안", best:"필요한 정보가 생기면 답하면 된다.", reframe:"일반적인 업무 표현이다." },
  { cat:"E", trigger:"“Thanks.”", misread:"차갑다", emotion:"서운함, 의심", best:"종료 신호로 받아들이고 추가 해석하지 않는다.", reframe:"간단히 끝낸 것일 수 있다." },
  { cat:"E", trigger:"“OK.”", misread:"불만이 있다", emotion:"불안, 경계심", best:"승인으로 해석하고 넘어간다.", reframe:null },
  { cat:"E", trigger:"“Noted.”", misread:"벽을 친다", emotion:"서운함, 답답함", best:"기록했다는 뜻으로만 본다.", reframe:"기록했다는 뜻이다." },
  { cat:"E", trigger:"“Fine.”", misread:"비꼰다", emotion:"불안, 의심", best:"맥락 없이는 판단 보류한다.", reframe:"맥락 없이는 판단 불가다." },
  { cat:"E", trigger:"“Sure.”", misread:"마지못해 한다", emotion:"의심, 서운함", best:"동의로 받아들이고 추가 의미를 붙이지 않는다.", reframe:"그냥 동의일 수 있다." },
  { cat:"E", trigger:"“Let’s discuss.”", misread:"문제가 있다", emotion:"긴장, 불안", best:"논의 목적을 확인한다.", reframe:"말로 정리하려는 것일 수 있다." },
  { cat:"E", trigger:"“Can you clarify?”", misread:"내가 불분명했다", emotion:"민망함, 방어심", best:"필요한 부분만 다시 설명한다.", reframe:"정보 보완 요청이다." },
  { cat:"E", trigger:"“I’m confused.”", misread:"내 설명이 엉망이다", emotion:"수치심, 불안", best:"상대가 헷갈린 지점을 묻는다.", reframe:"상대가 맥락을 놓쳤을 수 있다." },
  { cat:"E", trigger:"“I don’t follow.”", misread:"내가 못 설명했다", emotion:"민망함, 초조함", best:"단계별 설명으로 전환한다.", reframe:"단계별 설명이 필요한 것일 수 있다." },
  { cat:"E", trigger:"“Different from my understanding.”", misread:"충돌이다", emotion:"긴장, 방어심", best:"이해 차이를 비교한다.", reframe:"정보 alignment 필요다." },
  { cat:"E", trigger:"“Correct me if I’m wrong.”", misread:"방어적 공격이다", emotion:"경계심, 불쾌감", best:"사실 확인으로 답한다.", reframe:"정중한 확인 표현이다." },
  { cat:"E", trigger:"“Just checking.”", misread:"감시한다", emotion:"불안, 짜증", best:"단순 확인으로 보고 짧게 답한다.", reframe:"가벼운 확인이다." },
  { cat:"E", trigger:"“Can you resend?”", misread:"무시했다", emotion:"서운함, 짜증", best:"다시 보내고 파일명을 명확히 한다.", reframe:"파일을 못 찾았을 수 있다." },
  { cat:"E", trigger:"“I missed this.”", misread:"일부러 안 봤다", emotion:"서운함, 불쾌감", best:"재공유하고 다음 단계만 말한다.", reframe:"진짜 놓쳤을 수 있다." },
  { cat:"E", trigger:"“Sorry, busy.”", misread:"나는 우선순위가 아니다", emotion:"서운함, 실망", best:"다른 시간이나 written update로 전환한다.", reframe:"실제 일정 문제일 수 있다." },
  { cat:"E", trigger:"답장이 하루 늦음", misread:"나를 무시한다", emotion:"불안, 서운함", best:"일정 문제로 보고 필요 시 follow-up한다.", reframe:"상대 일정일 수 있다." },
  { cat:"E", trigger:"답장이 없음", misread:"거절이다", emotion:"불안, 무력감", best:"24~48시간 후 짧게 follow-up한다.", reframe:null },
  { cat:"E", trigger:"이모지가 없음", misread:"차갑다", emotion:"서운함, 의심", best:"업무 톤으로 받아들인다.", reframe:null },
  { cat:"E", trigger:"마침표가 딱딱함", misread:"화났다", emotion:"불안, 긴장", best:"문장 내용만 본다.", reframe:null },
  { cat:"E", trigger:"대문자 사용", misread:"소리친다", emotion:"긴장, 불쾌감", best:"강조인지 분노인지 맥락 확인한다.", reframe:null },
  { cat:"E", trigger:"“ASAP”", misread:"나를 몰아붙인다", emotion:"압박감, 짜증", best:"실제 deadline을 확인한다.", reframe:null },
  { cat:"E", trigger:"“Need this now”", misread:"무례하다", emotion:"분노, 부담감", best:"가능한 범위와 제약을 말한다.", reframe:"우선순위 문제일 수 있다." },
  { cat:"E", trigger:"“Can you explain?”", misread:"추궁한다", emotion:"방어심, 불안", best:"설명 요청으로 보고 facts를 준다.", reframe:null },
  { cat:"E", trigger:"“Why?” 한 단어", misread:"공격이다", emotion:"긴장, 분노", best:"배경을 묻는지 확인하고 짧게 답한다.", reframe:null },
  { cat:"E", trigger:"“Hmm”", misread:"마음에 안 든다", emotion:"불안, 의심", best:"추가 질문을 기다리거나 묻는다.", reframe:null },
  { cat:"E", trigger:"“Interesting…”", misread:"비꼰다", emotion:"경계심, 불쾌감", best:"구체적으로 어떤 점인지 묻는다.", reframe:"초기 호기심 표현일 수 있다." },
  { cat:"E", trigger:"“Let’s park this.”", misread:"묻어버린다", emotion:"좌절, 의심", best:"parking 이유와 revisit 시점을 묻는다.", reframe:"지금 결론 내기 어렵다는 뜻일 수 있다." },
  { cat:"E", trigger:"“We’ll see.”", misread:"거절이다", emotion:"불안, 실망", best:"결정 기준을 확인한다.", reframe:null },
  { cat:"E", trigger:"“Maybe.”", misread:"관심 없다", emotion:"실망, 답답함", best:"조건을 구체화한다.", reframe:null },
  { cat:"E", trigger:"“No worries.”", misread:"사실은 불만 있다", emotion:"의심, 불안", best:"그대로 받아들이고 과해석하지 않는다.", reframe:"우선순위 문제일 수 있다." },
  { cat:"E", trigger:"“Sounds good.”", misread:"대충 넘긴다", emotion:"의심, 서운함", best:"동의로 기록한다.", reframe:null },
  { cat:"E", trigger:"“Please confirm.”", misread:"못 믿는다", emotion:"방어심, 긴장", best:"확인해서 짧게 답한다.", reframe:"의견 요청일 수 있다." },
  { cat:"E", trigger:"“Reminder.”", misread:"독촉한다", emotion:"짜증, 압박감", best:"누락 방지로 보고 status를 답한다.", reframe:null },
  { cat:"E", trigger:"“Gentle reminder.”", misread:"압박을 포장한다", emotion:"짜증, 방어심", best:"감정 빼고 필요한 답만 한다.", reframe:null },
  { cat:"E", trigger:"“Per my last email.”", misread:"공격한다", emotion:"불쾌감, 긴장", best:"이전 메일 확인 후 사실만 답한다.", reframe:null },
  { cat:"E", trigger:"“As discussed.”", misread:"내 책임으로 박는다", emotion:"경계심, 부담감", best:"논의 내용과 합의사항을 확인한다.", reframe:"단순 데이터에는 적합하다." },
  { cat:"E", trigger:"“For visibility.”", misread:"나를 공개적으로 압박한다", emotion:"불안, 방어심", best:"공개 스레드에서는 중립적으로 답한다.", reframe:null },
  { cat:"E", trigger:"“Looping in A.”", misread:"공격 지원군을 부른다", emotion:"경계심, 불안", best:"역할 분담을 명확히 한다.", reframe:null },
  { cat:"E", trigger:"“Adding manager.”", misread:"escalation이다", emotion:"긴장, 압박감", best:"사실 중심으로 정리한다.", reframe:"리더십 한계일 수 있다." },
  { cat:"E", trigger:"“Can you own this?”", misread:"떠넘긴다", emotion:"부담감, 답답함", best:"ownership 범위와 due date를 명확히 한다.", reframe:null },
  { cat:"E", trigger:"“Quick question.”", misread:"사실 quick이 아닐 것이다", emotion:"피로감, 경계심", best:"질문 범위를 확인한다.", reframe:null },
  { cat:"E", trigger:"“Small request.”", misread:"일이 커질 것이다", emotion:"부담감, 짜증", best:"예상 effort를 먼저 말한다.", reframe:null },
  { cat:"E", trigger:"“Minor change.”", misread:"또 수정이다", emotion:"짜증, 피로감", best:"변경 범위와 impact를 확인한다.", reframe:null },
  { cat:"E", trigger:"“One more thing.”", misread:"끝이 없다", emotion:"피로감, 답답함", best:"추가 항목을 backlog로 넣는다.", reframe:"맥락 없이는 판단 불가다." },
  { cat:"E", trigger:"“Can you take a look?”", misread:"또 내 일이 된다", emotion:"부담감, 짜증", best:"확인 가능 범위와 시간을 제한한다.", reframe:null },
  { cat:"F", trigger:"내 말을 끊음", misread:"무시당했다", emotion:"분노, 수치심", best:"끊긴 지점으로 차분히 돌아온다.", reframe:null },
  { cat:"F", trigger:"질문이 많음", misread:"공격받는다", emotion:"긴장, 방어심", best:"질문을 관심과 검증으로 분리한다.", reframe:null },
  { cat:"F", trigger:"질문이 없음", misread:"관심 없다", emotion:"불안, 실망", best:"다음 action을 확인한다.", reframe:null },
  { cat:"F", trigger:"카메라 꺼짐", misread:"무례하다", emotion:"서운함, 불쾌감", best:"개인 사정이나 문화로 해석 보류한다.", reframe:"회사 문화나 환경 문제일 수 있다." },
  { cat:"F", trigger:"한숨을 쉼", misread:"내 발표가 별로다", emotion:"수치심, 불안", best:"상대 컨디션과 내 내용을 분리한다.", reframe:null },
  { cat:"F", trigger:"채팅이 조용함", misread:"반응이 나쁘다", emotion:"불안, 초조함", best:"이해 확인 질문을 던진다.", reframe:"다들 듣고 있을 수 있다." },
  { cat:"F", trigger:"한 사람이 반대함", misread:"전체가 반대한다", emotion:"긴장, 좌절", best:"반대 의견을 하나의 데이터로 본다.", reframe:"한 의견일 뿐이다." },
  { cat:"F", trigger:"매니저가 대신 답함", misread:"발언권을 뺏었다", emotion:"서운함, 무력감", best:"공식 톤 조율일 수 있어 기다린다.", reframe:"공식 톤을 조절한 것일 수 있다." },
  { cat:"F", trigger:"“시간 없으니 넘어가자”", misread:"내 파트 무시", emotion:"서운함, 분노", best:"follow-up 자료로 보완한다.", reframe:"agenda 관리일 수 있다." },
  { cat:"F", trigger:"action item이 나에게 옴", misread:"나만 떠맡는다", emotion:"부담감, 억울함", best:"범위와 due date를 명확히 한다.", reframe:null },
  { cat:"F", trigger:"회의 후 피드백 없음", misread:"실패했다", emotion:"불안, 실망", best:"짧게 확인 메일을 보낸다.", reframe:"문제 없어서 조용한 것일 수 있다." },
  { cat:"F", trigger:"회의 후 질문이 옴", misread:"발표가 부족했다", emotion:"민망함, 불안", best:"관심 신호로 보고 답한다.", reframe:"더 깊이 관심이 생겼을 수 있다." },
  { cat:"F", trigger:"누군가 내 자료를 다시 설명함", misread:"내 설명을 못 믿는다", emotion:"수치심, 방어심", best:"재표현을 alignment로 받아들인다.", reframe:"청중에게 재프레이밍한 것일 수 있다." },
  { cat:"F", trigger:"슬라이드 순서 수정 요청", misread:"구조가 틀렸다", emotion:"불안, 방어심", best:"청중 흐름 기준으로 재배치한다.", reframe:"협업 과정이다." },
  { cat:"F", trigger:"detail 줄이자", misread:"노력이 삭제된다", emotion:"허탈함, 서운함", best:"backup slide로 보존한다.", reframe:"청중이 executive level일 수 있다." },
  { cat:"F", trigger:"detail 더 넣자", misread:"빈약했다", emotion:"불안, 압박감", best:"기술 검토용 version을 만든다.", reframe:"기술 검토용 버전이 필요한 것이다." },
  { cat:"F", trigger:"회의 초대에서 빠짐", misread:"배제됐다", emotion:"서운함, 불안", best:"agenda 관련성을 확인한다.", reframe:"이번 agenda와 직접 관련이 없을 수 있다." },
  { cat:"F", trigger:"갑자기 회의 초대됨", misread:"공격받는다", emotion:"긴장, 경계심", best:"목적과 기대 input을 묻는다.", reframe:"네 input이 필요해졌을 수 있다." },
  { cat:"F", trigger:"다른 senior 참석", misread:"감시받는다", emotion:"불안, 방어심", best:"역할을 확인하고 자료로 대응한다.", reframe:"subject coverage 목적일 수 있다." },
  { cat:"F", trigger:"회의 제목이 애매함", misread:"함정이다", emotion:"경계심, 불안", best:"agenda를 요청한다.", reframe:"작성자가 대충 썼을 수 있다." },
  { cat:"F", trigger:"사람들이 딴청함", misread:"내 발표 무시", emotion:"수치심, 분노", best:"핵심 질문으로 다시 집중시킨다.", reframe:null },
  { cat:"F", trigger:"누군가 웃음", misread:"나를 비웃는다", emotion:"수치심, 불쾌감", best:"맥락 없으면 판단 보류한다.", reframe:null },
  { cat:"F", trigger:"내 말에 침묵", misread:"틀렸다", emotion:"불안, 초조함", best:"“Any concern?”으로 확인한다.", reframe:null },
  { cat:"F", trigger:"누가 “next”라고 함", misread:"내 파트 끝내려 한다", emotion:"서운함, 분노", best:"핵심 결론만 말하고 넘긴다.", reframe:null },
  { cat:"F", trigger:"질문이 공격적 톤", misread:"나를 깎는다", emotion:"방어심, 분노", best:"질문의 내용만 분리해서 답한다.", reframe:null },
  { cat:"F", trigger:"같은 질문 반복", misread:"일부러 괴롭힌다", emotion:"짜증, 피로감", best:"답변을 문서화해 공유한다.", reframe:"깊게 배우는 과정이다." },
  { cat:"F", trigger:"긴 미팅", misread:"내 시간 낭비", emotion:"답답함, 짜증", best:"agenda와 decision needed를 요청한다.", reframe:null },
  { cat:"F", trigger:"결론 없이 종료", misread:"무능하다", emotion:"피로감, 좌절", best:"action item summary를 보낸다.", reframe:null },
  { cat:"F", trigger:"내 의견이 채택 안 됨", misread:"무시당했다", emotion:"실망, 서운함", best:"결정 기준을 확인하고 기록한다.", reframe:null },
  { cat:"F", trigger:"다른 사람이 내 의견 반복 후 채택", misread:"공을 뺏겼다", emotion:"분노, 서운함", best:"내 최초 제안 기록을 남기고 감정 반응을 늦춘다.", reframe:null },
  { cat:"F", trigger:"발표 중 실수", misread:"내 신뢰도 추락", emotion:"수치심, 불안", best:"정정하고 계속 진행한다.", reframe:null },
  { cat:"F", trigger:"화면 공유 문제", misread:"준비 부족처럼 보임", emotion:"당황, 수치심", best:"침착하게 backup 파일을 사용한다.", reframe:null },
  { cat:"F", trigger:"질문에 즉답 못함", misread:"무능해 보인다", emotion:"불안, 수치심", best:"확인 후 답하겠다고 말한다.", reframe:null },
  { cat:"F", trigger:"누가 “good question”만 함", misread:"답 피한다", emotion:"의심, 답답함", best:"follow-up owner를 정한다.", reframe:null },
  { cat:"F", trigger:"회의가 갑자기 끝남", misread:"내 얘기 잘렸다", emotion:"서운함, 불안", best:"메일로 남은 내용을 보낸다.", reframe:null },
  { cat:"F", trigger:"누군가 내 이름 잘못 부름", misread:"존중 안 한다", emotion:"서운함, 불쾌감", best:"필요하면 부드럽게 정정한다.", reframe:null },
  { cat:"F", trigger:"내가 말할 타이밍 놓침", misread:"존재감 없다", emotion:"좌절, 수치심", best:"채팅이나 follow-up으로 의견을 남긴다.", reframe:null },
  { cat:"F", trigger:"내 자료를 안 봄", misread:"내 노력이 무시됐다", emotion:"허탈함, 분노", best:"자료 목적과 핵심만 다시 보낸다.", reframe:null },
  { cat:"F", trigger:"회의에서 내 일만 문제 삼음", misread:"표적이 됐다", emotion:"경계심, 불안", best:"이슈와 개인 평가를 분리한다.", reframe:null },
  { cat:"F", trigger:"회의 후 누가 따로 메시지", misread:"뒤에서 문제 삼는다", emotion:"불안, 의심", best:"내용 확인 전까지 단정하지 않는다.", reframe:null },
  { cat:"F", trigger:"meeting invite without context", misread:"함정이다", emotion:"긴장, 경계심", best:"agenda 요청한다.", reframe:null },
  { cat:"F", trigger:"“optional” 초대", misread:"나를 중요하게 안 본다", emotion:"서운함, 불안", best:"참석 필요성을 판단한다.", reframe:null },
  { cat:"F", trigger:"recurring meeting 추가", misread:"계속 감시한다", emotion:"답답함, 부담감", best:"목적과 cadence를 확인한다.", reframe:"그냥 동의일 수 있다." },
  { cat:"F", trigger:"회의록에 내 말 누락", misread:"기여 삭제", emotion:"서운함, 분노", best:"정중히 correction을 보낸다.", reframe:null },
  { cat:"F", trigger:"action owner가 틀림", misread:"책임 떠넘김", emotion:"불쾌감, 부담감", best:"owner를 바로잡는다.", reframe:"우선순위 문제일 수 있다." },
  { cat:"F", trigger:"내 질문이 무시됨", misread:"나를 낮게 본다", emotion:"서운함, 분노", best:"다시 짧게 질문한다.", reframe:null },
  { cat:"F", trigger:"누가 “offline으로 하자”", misread:"공개 논의를 피한다", emotion:"의심, 답답함", best:"offline 결과를 기록으로 남긴다.", reframe:"맥락 없이는 판단 불가다." },
  { cat:"F", trigger:"회의가 갑자기 취소", misread:"내 일이 중요하지 않다", emotion:"실망, 불안", best:"async update로 대체한다.", reframe:null },
  { cat:"F", trigger:"회의가 계속 연기", misread:"일부러 늦춘다", emotion:"좌절, 의심", best:"decision deadline을 제안한다.", reframe:null },
  { cat:"F", trigger:"회의가 너무 이른 시간", misread:"내 사정 무시", emotion:"짜증, 피로감", best:"가능한 시간대를 제안한다.", reframe:null },
  { cat:"G", trigger:"칭찬이 없음", misread:"인정받지 못했다", emotion:"서운함, 공허함", best:"명시적 칭찬보다 결과 기록을 남긴다.", reframe:"조용히 신뢰가 쌓일 수 있다." },
  { cat:"G", trigger:"내 툴 언급 없음", misread:"공이 사라졌다", emotion:"서운함, 분노", best:"contribution log를 유지한다.", reframe:null },
  { cat:"G", trigger:"다른 사람이 발표", misread:"내가 지워졌다", emotion:"질투, 서운함", best:"내 역할과 input을 문서로 남긴다.", reframe:"조직 메시지 역할일 수 있다." },
  { cat:"G", trigger:"“team effort”", misread:"내 기여 희석", emotion:"서운함, 경계심", best:"개인 기여 evidence를 따로 보존한다.", reframe:"조직 언어일 수 있다." },
  { cat:"G", trigger:"manager가 고객에게 말 안 함", misread:"숨긴다", emotion:"의심, 좌절", best:"적절한 visibility 채널을 찾는다.", reframe:"타이밍 조절일 수 있다." },
  { cat:"G", trigger:"동료가 내 아이디어 반복", misread:"훔쳤다", emotion:"분노, 경계심", best:"최초 공유 기록을 남긴다.", reframe:"이해해서 재표현한 것일 수 있다." },
  { cat:"G", trigger:"내 이름 빠짐", misread:"고의 배제", emotion:"서운함, 분노", best:"정중히 이름 추가를 요청한다.", reframe:"문서 작성 실수일 수 있다." },
  { cat:"G", trigger:"피드백 늦음", misread:"관심 없다", emotion:"실망, 불안", best:"follow-up 시점을 정한다.", reframe:"바쁜 일정 때문일 수 있다." },
  { cat:"G", trigger:"승인 늦음", misread:"막는다", emotion:"답답함, 의심", best:"승인 절차와 bottleneck을 확인한다.", reframe:null },
  { cat:"G", trigger:"사용자 늘지 않음", misread:"가치 없다", emotion:"좌절, 무력감", best:"adoption barrier를 분석한다.", reframe:"adoption은 시간이 걸린다." },
  { cat:"G", trigger:"일부 기능만 사용", misread:"전체 실패", emotion:"실망, 불안", best:"핵심 기능 adoption으로 본다.", reframe:"작은 기능부터 신뢰가 생기는 것이다." },
  { cat:"G", trigger:"질문만 많고 칭찬 없음", misread:"인정 안 한다", emotion:"서운함, 피로감", best:"검토 단계로 해석한다.", reframe:"조용한 신뢰도 존재한다." },
  { cat:"G", trigger:"“interesting”만 들음", misread:"애매한 거절", emotion:"불안, 답답함", best:"next step을 묻는다.", reframe:"초기 호기심 표현일 수 있다." },
  { cat:"G", trigger:"“good start”", misread:"아직 별로다", emotion:"수치심, 실망", best:"발전 가능성 인정으로 받아들인다.", reframe:"발전 가능성 인정일 수 있다." },
  { cat:"G", trigger:"“prototype”", misread:"장난감 취급", emotion:"서운함, 불쾌감", best:"prototype의 목적과 next maturity를 정의한다.", reframe:"제품화 전 단계라는 뜻이다." },
  { cat:"G", trigger:"“personal project”", misread:"공식 가치 없음", emotion:"실망, 수치심", best:"공식화 가능한 요소를 분리한다.", reframe:"현재 소유 구조를 말한 것일 수 있다." },
  { cat:"G", trigger:"“tool”이라고만 부름", misread:"제품 비전 축소", emotion:"서운함, 답답함", best:"현재 단계에서는 tool로 설명한다.", reframe:"업무에서는 보통 그렇게 부른다." },
  { cat:"G", trigger:"도움을 당연시함", misread:"이용당한다", emotion:"억울함, 피로감", best:"boundary와 support channel을 정한다.", reframe:null },
  { cat:"G", trigger:"“Thanks for helping”", misread:"owner가 아니다", emotion:"서운함, 불안", best:"내 contribution을 기록한다.", reframe:"상황별 감사 표현이다." },
  { cat:"G", trigger:"“Can you support this?”", misread:"잡일 떠넘긴다", emotion:"부담감, 답답함", best:"support 범위를 명확히 한다.", reframe:"신뢰받는 담당으로 보일 수 있다." },
  { cat:"G", trigger:"누가 내 결과를 자기 성과처럼 말함", misread:"빼앗겼다", emotion:"분노, 배신감", best:"감정 반응 전 기록과 증거를 정리한다.", reframe:null },
  { cat:"G", trigger:"내 자료가 수정되어 공유됨", misread:"내 의도가 왜곡됐다", emotion:"불안, 불쾌감", best:"원본과 수정본 차이를 확인한다.", reframe:null },
  { cat:"G", trigger:"내 tool 이름이 빠짐", misread:"identity가 지워졌다", emotion:"서운함, 분노", best:"공식 이름과 설명을 다시 제안한다.", reframe:"문서 작성 실수일 수 있다." },
  { cat:"G", trigger:"팀이 내 방식만 사용하고 언급 없음", misread:"착취당한다", emotion:"허탈함, 억울함", best:"adoption evidence로 기록한다.", reframe:null },
  { cat:"G", trigger:"manager가 “우리 팀이 만들었다”라고 함", misread:"내 공 삭제", emotion:"분노, 서운함", best:"개인 기여를 1:1에서 차분히 정리한다.", reframe:"리더십 한계일 수 있다." },
  { cat:"G", trigger:"내 결과가 다른 프로젝트에 포함됨", misread:"흡수당했다", emotion:"불안, 경계심", best:"contribution/ownership boundary를 확인한다.", reframe:null },
  { cat:"G", trigger:"포상 대상에서 빠짐", misread:"나는 가치 없다", emotion:"좌절, 수치심", best:"평가 기준과 기록을 확인한다.", reframe:null },
  { cat:"G", trigger:"성과 리뷰에 언급 없음", misread:"노력 무의미", emotion:"무력감, 서운함", best:"self-evaluation에 evidence를 넣는다.", reframe:null },
  { cat:"G", trigger:"고객이 내 tool 칭찬하지만 내부 조용함", misread:"내부가 막는다", emotion:"의심, 답답함", best:"고객 피드백을 기록해 공유한다.", reframe:null },
  { cat:"G", trigger:"다른 사람이 “간단한 자동화”라 함", misread:"하찮게 본다", emotion:"분노, 수치심", best:"impact 수치로 설명한다.", reframe:null },
  { cat:"G", trigger:"내 시간절감 효과를 축소함", misread:"인정 안 한다", emotion:"억울함, 짜증", best:"before/after 기준을 재정의한다.", reframe:null },
  { cat:"G", trigger:"내 tool을 쓰면서 부정적 말함", misread:"위선적이다", emotion:"분노, 경계심", best:"사용 여부와 의견을 분리한다.", reframe:null },
  { cat:"G", trigger:"아무도 ownership 안 줌", misread:"책임만 있고 권한 없다", emotion:"답답함, 억울함", best:"역할과 권한을 명확히 요구한다.", reframe:null },
  { cat:"G", trigger:"공은 팀, 버그는 나", misread:"불공정하다", emotion:"분노, 억울함", best:"issue ownership과 contribution을 분리 기록한다.", reframe:null },
  { cat:"G", trigger:"내 결과물이 표준이 됨", misread:"좋은데 이름은 사라짐", emotion:"복합감정, 서운함", best:"표준화 전 기여 기록을 확보한다.", reframe:null },
  { cat:"G", trigger:"칭찬받으면 불편함", misread:"내가 자만할까", emotion:"불안, 어색함", best:"감사히 받고 사실로 저장한다.", reframe:null },
  { cat:"G", trigger:"인정받고 싶음", misread:"내가 약하다", emotion:"수치심, 외로움", best:"인간적 욕구로 인정하고 기록 기반으로 간다.", reframe:"두려움인지 전략인지 구분한다." },
  { cat:"G", trigger:"자랑하고 싶음", misread:"품위 없어질까", emotion:"갈등, 불안", best:"문제-해결-효과 구조로 공유한다.", reframe:"두려움인지 전략인지 구분한다." },
  { cat:"G", trigger:"숨기고 싶음", misread:"빼앗길까", emotion:"경계심, 불안", best:"공개 범위와 타이밍을 설계한다.", reframe:"두려움인지 전략인지 구분한다." },
  { cat:"G", trigger:"더 보여주고 싶음", misread:"욕심인가", emotion:"기대, 불안", best:"readiness checklist 후 공유한다.", reframe:"두려움인지 전략인지 구분한다." },
  { cat:"G", trigger:"남이 인정받음", misread:"나는 밀렸다", emotion:"질투, 열등감", best:"내 evidence를 쌓고 비교를 줄인다.", reframe:null },
  { cat:"G", trigger:"내 성과가 늦게 보임", misread:"실패다", emotion:"조급함, 불안", best:"visibility plan을 만든다.", reframe:null },
  { cat:"G", trigger:"“잘했다”보다 수정만 받음", misread:"못했다", emotion:"서운함, 수치심", best:"수정은 제품화 과정으로 본다.", reframe:null },
  { cat:"G", trigger:"결과가 당연시됨", misread:"나는 도구처럼 쓰인다", emotion:"허탈함, 분노", best:"effort와 impact를 문서화한다.", reframe:null },
  { cat:"G", trigger:"내 이름이 너무 자주 나오면", misread:"미움받을까", emotion:"불안, 조심성", best:"팀 언어와 개인 기록을 병행한다.", reframe:"문서 작성 실수일 수 있다." },
  { cat:"G", trigger:"기여를 말해야 함", misread:"구차하다", emotion:"수치심, 저항감", best:"성과 기록은 방어가 아니라 업무다.", reframe:null },
  { cat:"G", trigger:"인정 못 받으면 공부로 도망", misread:"불안하다", emotion:"불안, 공허함", best:"감정 안정 후 다음 행동을 정한다.", reframe:null },
  { cat:"G", trigger:"보상 없음", misread:"회사가 나를 모른다", emotion:"좌절, 분노", best:"장기 포트폴리오 관점으로 정리한다.", reframe:null },
  { cat:"G", trigger:"평가 낮을까 걱정", misread:"나는 부족하다", emotion:"불안, 수치심", best:"성과 증거를 월별로 정리한다.", reframe:null },
  { cat:"G", trigger:"누가 내 성과를 의심", misread:"또 무시당한다", emotion:"분노, 방어심", best:"감정 반응 대신 근거를 보여준다.", reframe:null },
  { cat:"H", trigger:"“아직 공부 중이지?”", misread:"초보 취급", emotion:"수치심, 방어심", best:"배우는 중임을 강점으로 받아들인다.", reframe:"성장 과정을 인정하는 말일 수 있다." },
  { cat:"H", trigger:"“advanced topic이야.”", misread:"넌 아직 못한다", emotion:"열등감, 불안", best:"순서를 나눠 학습한다.", reframe:"난이도 안내일 수 있다." },
  { cat:"H", trigger:"“기본부터 다시 보자.”", misread:"기초도 없다", emotion:"수치심, 실망", best:"foundation 강화로 본다.", reframe:"안정적 학습 전략일 수 있다." },
  { cat:"H", trigger:"“너무 빨리 가는 것 같아.”", misread:"무리한다고 비판", emotion:"불안, 반발심", best:"속도와 소화율을 점검한다.", reframe:"소화 속도 걱정일 수 있다." },
  { cat:"H", trigger:"“천천히 해.”", misread:"성과 낮추라는 뜻", emotion:"답답함, 조급함", best:"지속 가능한 pace로 바꾼다.", reframe:"지속 가능성을 위한 조언일 수 있다." },
  { cat:"H", trigger:"“나중에 이해될 거야.”", misread:"지금은 못 알아듣는다", emotion:"수치심, 답답함", best:"반복 학습 대상으로 저장한다.", reframe:"학습 순서의 문제다." },
  { cat:"H", trigger:"에러 발생", misread:"재능 없다", emotion:"좌절, 불안", best:"에러 메시지를 데이터로 읽는다.", reframe:null },
  { cat:"H", trigger:"모듈 설치 실패", misread:"개발과 안 맞다", emotion:"답답함, 무력감", best:"환경 문제와 코드 문제를 분리한다.", reframe:"개발자의 일상이다." },
  { cat:"H", trigger:"이해가 늦음", misread:"머리가 나쁘다", emotion:"수치심, 불안", best:"반복 횟수를 늘린다.", reframe:"새로운 개념은 반복이 필요하다." },
  { cat:"H", trigger:"같은 질문 반복", misread:"나는 못 배운다", emotion:"실망, 자책", best:"더 깊게 연결 중이라고 본다.", reframe:"깊게 배우는 과정이다." },
  { cat:"H", trigger:"JS가 헷갈림", misread:"개발자 타입 아님", emotion:"불안, 열등감", best:"언어 차이로 보고 Python과 비교한다.", reframe:null },
  { cat:"H", trigger:"JS가 재미있음", misread:"본업 도피", emotion:"죄책감, 불안", best:"학습 에너지로 인정한다.", reframe:"학습 동기가 생긴 것이다." },
  { cat:"H", trigger:"class 어려움", misread:"OOP 재능 없음", emotion:"좌절, 수치심", best:"객체 모델을 작은 예시로 반복한다.", reframe:null },
  { cat:"H", trigger:"dict/JSON에 감동", misread:"너무 늦게 알았다", emotion:"민망함, 후회", best:"구조를 이해한 신호로 본다.", reframe:"이제 연결되기 시작한 것이다." },
  { cat:"H", trigger:"DOM 이해 느림", misread:"웹 못한다", emotion:"답답함, 불안", best:"트리 구조와 메모리 모델로 다시 본다.", reframe:null },
  { cat:"H", trigger:"Tauri 빌드 실패", misread:"프로젝트 망함", emotion:"좌절, 짜증", best:"빌드 환경 체크리스트를 만든다.", reframe:"환경 세팅은 별도 문제다." },
  { cat:"H", trigger:"linker 에러", misread:"내 코드 문제", emotion:"불안, 당황", best:"toolchain 문제로 분리한다.", reframe:null },
  { cat:"H", trigger:"pandas 에러", misread:"데이터 분석 안 맞음", emotion:"좌절, 수치심", best:"입력/형식/권한 문제를 확인한다.", reframe:"입력/환경 문제일 수 있다." },
  { cat:"H", trigger:"regex 헷갈림", misread:"기초 부족", emotion:"민망함, 불안", best:"작은 패턴부터 테스트한다.", reframe:"regex는 모두가 헷갈린다." },
  { cat:"H", trigger:"모델링 개념이 넓음", misread:"내가 이상하게 생각", emotion:"혼란, 흥미", best:"좋은 추상화 질문으로 기록한다.", reframe:"좋은 추상화 능력이다." },
  { cat:"H", trigger:"코드 리뷰 받음", misread:"내가 부족하다", emotion:"수치심, 방어심", best:"코드 품질 향상 과정으로 본다.", reframe:null },
  { cat:"H", trigger:"“테스트 필요”", misread:"못 믿는다", emotion:"불안, 방어심", best:"test case를 추가한다.", reframe:null },
  { cat:"H", trigger:"“문서화 필요”", misread:"설명 부족", emotion:"민망함, 불안", best:"README와 usage example을 만든다.", reframe:null },
  { cat:"H", trigger:"“성능 측정 필요”", misread:"느릴 거라 본다", emotion:"긴장, 방어심", best:"benchmark를 만든다.", reframe:null },
  { cat:"H", trigger:"“메모리 조심”", misread:"설계가 틀렸다", emotion:"불안, 수치심", best:"대용량 조건을 따로 테스트한다.", reframe:null },
  { cat:"H", trigger:"“streaming 써야 해”", misread:"지금 방식 실패", emotion:"좌절, 불안", best:"file size 기준으로 전략을 나눈다.", reframe:"대용량 최적화다." },
  { cat:"H", trigger:"“class로 바꿔”", misread:"구조가 나쁘다", emotion:"방어심, 수치심", best:"확장성 요구로 본다.", reframe:null },
  { cat:"H", trigger:"“dict로 충분해”", misread:"과하게 만들었다", emotion:"민망함, 불안", best:"단순성과 확장성을 비교한다.", reframe:null },
  { cat:"H", trigger:"“CLI 지원해”", misread:"지금 불편하다", emotion:"압박감, 불안", best:"input method 확장으로 본다.", reframe:null },
  { cat:"H", trigger:"“GUI 필요해”", misread:"현재는 못 쓴다", emotion:"실망, 부담감", best:"사용자 접근성 개선으로 본다.", reframe:null },
  { cat:"H", trigger:"하루 공부 못함", misread:"퇴보했다", emotion:"불안, 죄책감", best:"다음날 최소 단위로 복귀한다.", reframe:"한 번 빠진 것뿐이다." },
  { cat:"H", trigger:"오후 집중 안 됨", misread:"의지 부족", emotion:"자책, 답답함", best:"오후는 low-energy task로 배치한다.", reframe:null },
  { cat:"H", trigger:"프로젝트 많음", misread:"산만하다", emotion:"불안, 혼란", best:"idea bank와 active project를 분리한다.", reframe:"pipeline으로 관리하면 portfolio다." },
  { cat:"H", trigger:"새 아이디어 생김", misread:"또 도망간다", emotion:"죄책감, 흥분", best:"기록만 하고 실행은 나중에 결정한다.", reframe:"idea bank에 넣으면 된다." },
  { cat:"H", trigger:"코드가 지저분함", misread:"난 미숙하다", emotion:"수치심, 불안", best:"refactoring backlog로 옮긴다.", reframe:null },
  { cat:"H", trigger:"남의 코드가 좋아 보임", misread:"난 부족하다", emotion:"열등감, 불안", best:"좋은 패턴을 배운다.", reframe:null },
  { cat:"H", trigger:"AI 도움 받음", misread:"내 실력 아니다", emotion:"수치심, 의심", best:"이해하고 적용한 부분을 내 실력으로 만든다.", reframe:null },
  { cat:"H", trigger:"모르는 게 많음", misread:"경쟁력 없다", emotion:"불안, 무력감", best:"모르는 목록을 roadmap으로 바꾼다.", reframe:null },
  { cat:"H", trigger:"공부가 느림", misread:"늦었다", emotion:"조급함, 후회", best:"장기 누적 관점으로 본다.", reframe:null },
  { cat:"H", trigger:"만든 게 작아 보임", misread:"하찮다", emotion:"실망, 자책", best:"작은 완성물을 portfolio brick으로 본다.", reframe:null },
  { cat:"H", trigger:"다시 기본으로 돌아감", misread:"퇴보", emotion:"좌절, 민망함", best:"depth가 생겼기 때문에 기본이 새롭게 보이는 것이다.", reframe:null },
  { cat:"H", trigger:"설명을 못함", misread:"이해 못한 것", emotion:"수치심, 불안", best:"말로 설명하는 연습을 추가한다.", reframe:null },
  { cat:"H", trigger:"책 진도 느림", misread:"게으르다", emotion:"죄책감, 불안", best:"실습 중심 학습으로 전환한다.", reframe:null },
  { cat:"H", trigger:"강의 이해 안 됨", misread:"머리 나쁘다", emotion:"좌절, 수치심", best:"다른 자료로 같은 개념을 본다.", reframe:null },
  { cat:"H", trigger:"실습 성공", misread:"운 좋았다", emotion:"의심, 불안", best:"재현해서 자신감으로 바꾼다.", reframe:null },
  { cat:"H", trigger:"실습 실패", misread:"재능 없다", emotion:"좌절, 분노", best:"실패 로그를 남긴다.", reframe:null },
  { cat:"H", trigger:"코드 복붙함", misread:"가짜 학습", emotion:"죄책감, 수치심", best:"한 줄씩 의미를 해석한다.", reframe:null },
  { cat:"H", trigger:"도움 요청", misread:"약해 보인다", emotion:"수치심, 불안", best:"정확한 질문은 실력으로 본다.", reframe:null },
  { cat:"H", trigger:"이해한 순간 감동", misread:"내가 유치한가", emotion:"민망함, 기쁨", best:"감동은 학습 동력으로 보존한다.", reframe:null },
  { cat:"H", trigger:"배우는 게 즐거움", misread:"현실 도피인가", emotion:"불안, 죄책감", best:"현실을 해결하는 방향인지 확인한다.", reframe:null },
  { cat:"I", trigger:"경력 많은 사람 봄", misread:"난 경쟁력 없다", emotion:"열등감, 불안", best:"경험 종류가 다르다고 분리한다.", reframe:null },
  { cat:"I", trigger:"발표 잘하는 사람 봄", misread:"난 부족하다", emotion:"수치심, 비교심", best:"내 강점은 문제 해결과 구현임을 기억한다.", reframe:null },
  { cat:"I", trigger:"정치 잘하는 사람 봄", misread:"내가 뒤처졌다", emotion:"불안, 분노", best:"내 방식의 visibility 전략을 만든다.", reframe:null },
  { cat:"I", trigger:"빨리 인정받는 사람 봄", misread:"내 노력은 헛되다", emotion:"질투, 좌절", best:"시간축이 다르다고 본다.", reframe:null },
  { cat:"I", trigger:"말 잘 포장하는 사람 봄", misread:"내가 손해 본다", emotion:"불안, 답답함", best:"내 결과를 한 문장으로 포장하는 연습을 한다.", reframe:null },
  { cat:"I", trigger:"자신감 있는 동료", misread:"내가 작아진다", emotion:"열등감, 위축", best:"겉 자신감과 실제 결과를 분리한다.", reframe:null },
  { cat:"I", trigger:"나보다 높은 직급", misread:"나는 늦었다", emotion:"불안, 후회", best:"방향과 축적을 본다.", reframe:null },
  { cat:"I", trigger:"어린 사람이 잘함", misread:"난 늦었다", emotion:"열등감, 조급함", best:"나만의 도메인 자산을 확인한다.", reframe:"축적된 도메인 경험은 별도 자산이다." },
  { cat:"I", trigger:"AI 잘 쓰는 사람", misread:"대체될까", emotion:"불안, 위기감", best:"도메인+AI 조합을 강화한다.", reframe:null },
  { cat:"I", trigger:"개발자 출신과 비교", misread:"난 비전공자", emotion:"수치심, 불안", best:"현장 문제를 아는 builder로 본다.", reframe:"현장 문제를 아는 builder라는 강점이 있다." },
  { cat:"I", trigger:"데이터 사이언티스트 비교", misread:"난 애매하다", emotion:"불안, 정체성 혼란", best:"장비/공정/데이터 연결 강점을 본다.", reframe:"너는 장비/공정/데이터를 연결한다." },
  { cat:"I", trigger:"고객 앞 유창한 사람", misread:"난 부족하다", emotion:"수치심, 비교심", best:"정확성과 신뢰도도 능력이다.", reframe:"정확함과 신뢰도도 중요하다." },
  { cat:"I", trigger:"과거 낮은 평가 기억", misread:"난 원래 부족하다", emotion:"수치심, 분노", best:"과거 평가는 전체 정체성이 아니다.", reframe:null },
  { cat:"I", trigger:"무시했던 동료 기억", misread:"증명해야 한다", emotion:"분노, 복수심", best:"증명이 아니라 성장에 집중한다.", reframe:null },
  { cat:"I", trigger:"남이 쉬워 보임", misread:"나만 힘들다", emotion:"외로움, 열등감", best:"내부 전투는 보이지 않는다고 본다.", reframe:"내부 전투는 밖에서 안 보인다." },
  { cat:"I", trigger:"portfolio 부족해 보임", misread:"아무것도 아니다", emotion:"불안, 자책", best:"만든 결과물을 목록화한다.", reframe:null },
  { cat:"I", trigger:"“진짜 개발자” 기준", misread:"나는 가짜", emotion:"수치심, 의심", best:"문제를 해결하면 개발이다.", reframe:"문제를 해결하면 개발이다." },
  { cat:"I", trigger:"전문가 기준", misread:"나는 멀었다", emotion:"불안, 겸손", best:"계속 모르는 게 정상이다.", reframe:"전문가도 계속 모른다." },
  { cat:"I", trigger:"지식의 빙산 느낌", misread:"나는 작다", emotion:"경외감, 불안", best:"배움의 시작으로 본다.", reframe:"진짜 배움의 시작이다." },
  { cat:"I", trigger:"공부할 게 많음", misread:"압도된다", emotion:"불안, 혼란", best:"roadmap과 우선순위를 만든다.", reframe:"roadmap이 필요한 것이다." },
  { cat:"I", trigger:"누가 무시하는 말투", misread:"과거가 반복된다", emotion:"분노, 경계심", best:"현재 사람과 과거 사람을 분리한다.", reframe:"현재 사람과 과거 사람을 분리한다." },
  { cat:"I", trigger:"애매한 질문", misread:"공격이다", emotion:"긴장, 방어심", best:"질문 목적을 확인한다.", reframe:null },
  { cat:"I", trigger:"피드백", misread:"나는 문제 있는 사람", emotion:"수치심, 자책", best:"업무 수정과 정체성을 분리한다.", reframe:null },
  { cat:"I", trigger:"칭찬 없음", misread:"인정 못 받음", emotion:"서운함, 공허함", best:"evidence를 남기고 기다린다.", reframe:"조용한 신뢰도 존재한다." },
  { cat:"I", trigger:"실수", misread:"역시 부족함", emotion:"수치심, 불안", best:"수정하고 재발 방지한다.", reframe:null },
  { cat:"I", trigger:"불친절한 말", misread:"회사 전체가 나를 싫어함", emotion:"분노, 외로움", best:"한 사람의 커뮤니케이션으로 제한한다.", reframe:"한 사람의 톤일 수 있다." },
  { cat:"I", trigger:"늦은 답장", misread:"버림받음", emotion:"불안, 서운함", best:"follow-up template을 사용한다.", reframe:"업무 queue일 수 있다." },
  { cat:"I", trigger:"제외됨", misread:"배척당함", emotion:"서운함, 불안", best:"agenda 관련성을 확인한다.", reframe:"agenda mismatch일 수 있다." },
  { cat:"I", trigger:"반대 의견", misread:"공격", emotion:"방어심, 분노", best:"리스크 관점으로 해석한다.", reframe:"품질 개선 과정일 수 있다." },
  { cat:"I", trigger:"조롱처럼 들림", misread:"바로 복수심", emotion:"분노, 수치심", best:"현재의 품위를 우선한다.", reframe:"지금은 이미 앞서가고 있다." },
  { cat:"I", trigger:"“너 요즘…”", misread:"평가받는다", emotion:"불안, 경계심", best:"구체적으로 어떤 점인지 묻는다.", reframe:null },
  { cat:"I", trigger:"“왜 아직…”", misread:"비난", emotion:"압박감, 억울함", best:"현재 상태와 blocker를 말한다.", reframe:"일정 확인일 수 있다." },
  { cat:"I", trigger:"“다시 해줘”", misread:"무능 판정", emotion:"수치심, 좌절", best:"수정 요청으로만 처리한다.", reframe:"수정 요청일 뿐이다." },
  { cat:"I", trigger:"“잘 모르겠는데”", misread:"내 설명 부정", emotion:"민망함, 불안", best:"상대 context를 확인한다.", reframe:"상대 배경지식 문제일 수 있다." },
  { cat:"I", trigger:"“별 차이 없어 보여”", misread:"내 노력 삭제", emotion:"허탈함, 분노", best:"지표 기준으로 다시 본다.", reframe:"데이터 기준이 다를 수 있다." },
  { cat:"I", trigger:"“너무 복잡해”", misread:"내 사고가 이상함", emotion:"수치심, 방어심", best:"UX 단순화 신호로 본다.", reframe:"사용자 관점 피드백이다." },
  { cat:"I", trigger:"“필요 없어”", misread:"내가 필요 없다", emotion:"서운함, 무력감", best:"기능 필요성과 자기 가치를 분리한다.", reframe:"특정 기능의 필요성이 낮은 것이다." },
  { cat:"I", trigger:"감정이 올라옴", misread:"아직 약하다", emotion:"자책, 불안", best:"감지를 잘한 것으로 기록한다.", reframe:"감지를 잘하고 있다는 신호다." },
  { cat:"I", trigger:"바로 반박하고 싶음", misread:"지금 싸워야 한다", emotion:"분노, 방어심", best:"10분 delay 후 답한다.", reframe:"두려움인지 전략인지 구분한다." },
  { cat:"I", trigger:"억울함", misread:"즉시 정정해야 한다", emotion:"분노, 초조함", best:"기록 후 차분히 정정한다.", reframe:null },
  { cat:"I", trigger:"상대 표정 안 좋음", misread:"나 때문", emotion:"불안, 눈치", best:"근거 없으면 판단 보류한다.", reframe:"그 사람 컨디션일 수 있다." },
  { cat:"I", trigger:"짧은 답", misread:"나를 싫어함", emotion:"서운함, 의심", best:"스타일로 보고 넘어간다.", reframe:"업무 간결성일 수 있다." },
  { cat:"I", trigger:"무례한 질문", misread:"내 가치 낮춤", emotion:"분노, 수치심", best:"질문 내용만 답한다.", reframe:"질문의 질이 낮을 뿐 내 가치와 별개다." },
  { cat:"I", trigger:"상대가 아는 척", misread:"화남", emotion:"분노, 경멸", best:"사실 기준으로만 정리한다.", reframe:null },
  { cat:"I", trigger:"manager 애매함", misread:"숨은 의도", emotion:"불안, 의심", best:"명확한 질문으로 바꾼다.", reframe:"리더십 한계일 수 있다." },
  { cat:"I", trigger:"나만 일함", misread:"이용당함", emotion:"억울함, 피로감", best:"boundary를 설정한다.", reframe:null },
  { cat:"I", trigger:"빨리 해결함", misread:"또 당연해짐", emotion:"불안, 부담감", best:"speed보다 process를 남긴다.", reframe:"속도보다 전달 방식을 조절한다." },
  { cat:"I", trigger:"거절", misread:"나 자체 거절", emotion:"수치심, 실망", best:"제안의 timing 거절로 본다.", reframe:null },
  { cat:"I", trigger:"수정 요청", misread:"실패", emotion:"좌절, 수치심", best:"품질 개선으로 처리한다.", reframe:"협업 과정이다." },
  { cat:"I", trigger:"기다림", misread:"기회 상실", emotion:"조급함, 불안", best:"체크포인트를 설정한다.", reframe:"타이밍 전략일 수 있다." },
  { cat:"J", trigger:"업체 답 늦음", misread:"나를 무시", emotion:"짜증, 불안", best:"정중한 follow-up을 보낸다.", reframe:"일정이 밀렸을 수 있다." },
  { cat:"J", trigger:"HOA conditional approval", misread:"또 문제 삼음", emotion:"불안, 피로감", best:"조건을 체크리스트로 처리한다.", reframe:"승인 과정의 조건일 수 있다." },
  { cat:"J", trigger:"추가 수정 요구", misread:"괴롭힌다", emotion:"좌절, 분노", best:"규정 항목과 시공 항목을 분리한다.", reframe:"규정 적용일 수 있다." },
  { cat:"J", trigger:"contractor가 못 옴", misread:"책임감 없다", emotion:"짜증, 답답함", best:"가능한 날짜를 다시 잡는다.", reframe:"스케줄 문제일 수 있다." },
  { cat:"J", trigger:"비용 예상 초과", misread:"바가지", emotion:"불안, 분노", best:"itemized quote를 요청한다.", reframe:null },
  { cat:"J", trigger:"pest control full charge", misread:"속였다", emotion:"분노, 억울함", best:"reservice 근거와 취소 요청을 보낸다.", reframe:"서비스 코드 오해일 수 있다." },
  { cat:"J", trigger:"regular service 안내 누락", misread:"배려 없다", emotion:"짜증, 억울함", best:"사전 안내 부재를 차분히 언급한다.", reframe:"사전 안내 누락일 수 있다." },
  { cat:"J", trigger:"집에 없을 때 서비스", misread:"무시당함", emotion:"분노, 답답함", best:"scheduling preference를 명확히 알린다.", reframe:"scheduling communication gap이다." },
  { cat:"J", trigger:"HOA 답장 늦음", misread:"불리하게 처리", emotion:"불안, 의심", best:"follow-up과 기록 보존을 한다.", reframe:"담당자 queue 문제일 수 있다." },
  { cat:"J", trigger:"배송 문구 고민", misread:"문제 생길까", emotion:"불안, 긴장", best:"정확하고 일반적인 description을 쓴다.", reframe:null },
  { cat:"J", trigger:"아내가 앱 개선 요청", misread:"결과물이 부족", emotion:"민망함, 불안", best:"실제 사용자 피드백으로 받는다.", reframe:"실제 사용자 피드백이다." },
  { cat:"J", trigger:"아내가 현실 조언", misread:"꿈을 막음", emotion:"서운함, 방어심", best:"생활 균형 조언으로 듣는다.", reframe:"생활 균형을 보는 것이다." },
  { cat:"J", trigger:"집안일 지적", misread:"못하는 남편", emotion:"수치심, 죄책감", best:"역할을 구체적으로 조정한다.", reframe:"역할 조율 문제다." },
  { cat:"J", trigger:"육아 의견 차이", misread:"부족한 아빠", emotion:"불안, 죄책감", best:"함께 배우는 과정으로 본다.", reframe:null },
  { cat:"J", trigger:"아기가 힘들어함", misread:"내가 잘못함", emotion:"죄책감, 불안", best:"아기의 상태와 내 책임을 분리한다.", reframe:"아기는 원래 예측 불가다." },
  { cat:"J", trigger:"가족 때문에 공부 줄어듦", misread:"성장 멈춤", emotion:"불안, 답답함", best:"가족 시간과 학습 최소량을 재설계한다.", reframe:"장기 리듬 조정이다." },
  { cat:"J", trigger:"피곤해서 예민함", misread:"약하다", emotion:"자책, 무력감", best:"회복을 우선한다.", reframe:"회복이 필요한 신호다." },
  { cat:"J", trigger:"아내가 조용함", misread:"실망했다", emotion:"불안, 의심", best:"피곤함 가능성을 먼저 본다.", reframe:"단순히 피곤할 수 있다." },
  { cat:"J", trigger:"부탁받음", misread:"시간이 뺏긴다", emotion:"답답함, 부담감", best:"사랑하는 사람의 실제 need로 본다.", reframe:null },
  { cat:"J", trigger:"계획 틀어짐", misread:"하루 망함", emotion:"좌절, 짜증", best:"최소 단위 작업으로 재시작한다.", reframe:"최소 단위로 재시작하면 된다." },
  { cat:"J", trigger:"눈이 뿌옇다", misread:"큰 병", emotion:"불안, 공포", best:"증상 기록 후 검진을 예약한다.", reframe:"검진 필요하지만 피로/건조도 가능하다." },
  { cat:"J", trigger:"가까운 게 안 보임", misread:"노화가 왔다", emotion:"불안, 서글픔", best:"자연 변화 가능성과 검진을 함께 본다.", reframe:"자연스러운 변화일 수 있다." },
  { cat:"J", trigger:"눈부심", misread:"심각한 문제", emotion:"불안, 긴장", best:"악화 시 전문 검진을 받는다.", reframe:null },
  { cat:"J", trigger:"오후 집중 저하", misread:"의지 약함", emotion:"자책, 답답함", best:"오후는 가벼운 업무로 배치한다.", reframe:"바이오리듬 패턴일 수 있다." },
  { cat:"J", trigger:"허리 통증", misread:"몸이 망가짐", emotion:"불안, 좌절", best:"자세, 휴식, 진료 계획을 세운다.", reframe:"관리와 조절이 필요하다." },
  { cat:"J", trigger:"피곤함", misread:"게으름", emotion:"죄책감, 무력감", best:"수면과 회복을 점검한다.", reframe:"회복 부족일 수 있다." },
  { cat:"J", trigger:"머리 멍함", misread:"능력 저하", emotion:"불안, 자책", best:"컨디션 변수로 기록한다.", reframe:null },
  { cat:"J", trigger:"생각하며 말함", misread:"이상하다", emotion:"민망함, 불안", best:"사고 정리 방식으로 보고 상황별 조절한다.", reframe:null },
  { cat:"J", trigger:"말이 많아짐", misread:"문제 있다", emotion:"수치심, 불안", best:"핵심 요약 연습을 한다.", reframe:"진단보다 상황 패턴을 본다." },
  { cat:"J", trigger:"감정 올라옴", misread:"아직 약하다", emotion:"자책, 불안", best:"감지 후 행동을 늦춘다.", reframe:"감지를 잘하고 있다는 신호다." },
  { cat:"J", trigger:"오전만 잘됨", misread:"반쪽짜리", emotion:"불안, 자책", best:"오전에 deep work를 배치한다.", reframe:"최고의 시간대를 찾은 것이다." },
  { cat:"J", trigger:"오후 무너짐", misread:"실패", emotion:"좌절, 자책", best:"low-energy task로 전환한다.", reframe:"낮은 에너지 작업 시간이다." },
  { cat:"J", trigger:"하루 공부 못함", misread:"퇴보", emotion:"불안, 죄책감", best:"다음날 20분 복귀를 한다.", reframe:"한 번 빠진 것뿐이다." },
  { cat:"J", trigger:"계획보다 적게 함", misread:"망함", emotion:"실망, 자책", best:"완료한 것부터 기록한다.", reframe:"유지가 더 중요하다." },
  { cat:"J", trigger:"프로젝트 많음", misread:"산만", emotion:"불안, 혼란", best:"active / parked / idea로 나눈다.", reframe:"pipeline으로 관리하면 portfolio다." },
  { cat:"J", trigger:"한 프로젝트 중단", misread:"끈기 없음", emotion:"죄책감, 실망", best:"pause reason을 기록한다.", reframe:"우선순위 재조정일 수 있다." },
  { cat:"J", trigger:"새 아이디어", misread:"도망", emotion:"흥분, 죄책감", best:"idea bank에 넣고 실행 보류한다.", reframe:"idea bank에 넣으면 된다." },
  { cat:"J", trigger:"코딩 즐거움", misread:"현실 회피", emotion:"불안, 죄책감", best:"실제 문제 해결과 연결한다.", reframe:"건강한 몰입일 수 있다." },
  { cat:"J", trigger:"공부로 불안 완화", misread:"문제다", emotion:"불안, 의심", best:"균형을 점검하되 강점으로 쓴다.", reframe:null },
  { cat:"J", trigger:"쉬면 불안", misread:"뒤처진다", emotion:"초조함, 죄책감", best:"회복도 일정에 넣는다.", reframe:"회복도 성장의 일부다." },
  { cat:"J", trigger:"기능 요청", misread:"기존이 부족", emotion:"불안, 방어심", best:"살아있는 제품 피드백으로 본다.", reframe:null },
  { cat:"J", trigger:"버그 발견", misread:"실패", emotion:"수치심, 긴장", best:"bug report와 fix plan으로 전환한다.", reframe:"실제 사용이 시작됐다는 뜻이다." },
  { cat:"J", trigger:"UI 지적", misread:"별로다", emotion:"민망함, 실망", best:"usability 개선으로 기록한다.", reframe:"adoption을 위한 정보다." },
  { cat:"J", trigger:"기능 많음", misread:"과욕", emotion:"불안, 수치심", best:"기본/고급 모드를 나눈다.", reframe:null },
  { cat:"J", trigger:"기능 적음", misread:"부족", emotion:"불안, 압박감", best:"MVP 기준을 다시 확인한다.", reframe:null },
  { cat:"J", trigger:"문서 요청", misread:"불신", emotion:"방어심, 민망함", best:"제품화 필수 단계로 본다.", reframe:"제품화 필수 단계다." },
  { cat:"J", trigger:"배포 승인 대기", misread:"막힘", emotion:"조급함, 불안", best:"release process로 보고 기다린다.", reframe:"release process다." },
  { cat:"J", trigger:"아이콘 마음에 안 듦", misread:"감각 부족", emotion:"좌절, 짜증", best:"디자인 iteration으로 본다.", reframe:"디자인 iteration이다." },
  { cat:"J", trigger:"개인 앱이 작아 보임", misread:"하찮다", emotion:"실망, 자책", best:"실제 사용자 문제 해결로 평가한다.", reframe:null },
  { cat:"J", trigger:"Mind Debugger 개발", misread:"내가 문제가 많다", emotion:"수치심, 불안", best:"자기조절 시스템을 만드는 강점으로 본다.", reframe:"자기조절 도구를 만드는 것이다." },
]
